### ISSUE TITLE
Can't set breakpoints in test code

### ISSUE THREAD

**Issue by paymog** [KronicDeth/intellij-elixir#1051]
I'm new to using intellij-elixir. I've had a lot of success with running a pheonix server and debugging it. I'm finding that I can't set breakpoints in test code though. Is this expected behaviour? I scrolled through the README and didn't see anything mentioning this although I may have missed it. Is it possible to debug test code? 

I did see that one of the screenshots under the "Breakpoint" section is of tests being debugged. 

My configuration is: 
![image](https://user-images.githubusercontent.com/1986950/37190286-e358b918-230d-11e8-9dfc-f60ed77cc145.png)

My directory structure is:

![image](https://user-images.githubusercontent.com/1986950/37190303-f1216cc0-230d-11e8-973c-a94790bc5738.png)

And when I'm in a test file, the breakpoint menus are greyed out:

![image](https://user-images.githubusercontent.com/1986950/37190338-16496f16-230e-11e8-9f0c-f87cbeb0c759.png)

I don't know if this is relevant but it seems some part of my project is misconfigured because I can't [exclude modules](https://github.com/KronicDeth/intellij-elixir#excluding-modules):

![image](https://user-images.githubusercontent.com/1986950/37190428-7df5180e-230e-11e8-9c30-c3aee2db4943.png)

Ideas on what might be going on?

**Comment by KronicDeth** [comment]
> I'm finding that I can't set breakpoints in test code though. Is this expected behaviour? 

It's not that you can't set breakpoints in test code, it's that you can't set breakpoints in ElixirScript (`.exs`) files.  The debugger uses OTP's `:int` module (as does the debugger in `:debugger` and Elixir Language Server) to interpret the modules, which allows the line-based debugging.  `:int` requires there to be a `.beam` file on disk to load and get the Erlang Abstract Code from.  ElixirScripts don't compile to a `.beam`, they only remain in memory, so they're not debuggable with `:int`.

Supporting debugging them would involve changing the compilation process to produce a `.beam` for the test's `.exs`.  This may be possible, but it doesn't Just  Work™️. 

> I scrolled through the README and didn't see anything mentioning this although I may have missed it.

From [Creating Line Breakpoints](https://github.com/KronicDeth/intellij-elixir/blob/v7.4.0/README.md#creating-line-breakpoints)

>> Line break points can be set in .ex and .eex files.

In 7.4.0 you'd be able to debug any code-under-test in `.ex` and `.eex` files, so you can set breakpoints in and of the `test/support/**/*.ex` files or any `*.ex` files in your normal code that happens to be called from a `test`, but any code only in the `test` block won't accept a breakpoint.

> I did see that one of the screenshots under the "Breakpoint" section is of tests being debugged.

If you look closely at the file that is open, that's `test/support/conn_case.ex`, which is an `.ex` file, so that works because it will be compiled to a `.beam` file on-disk.

>  I can't exclude modules:

The subsection would be above the "Groovy" language section in the Stepping configuration.  If you don't see it, make sure you're using version 7.4.0 of the plugin.

**Comment by paymog** [comment]
Sorry for the late response, just got back from vacation.

Well, I feel silly. Should have realized they're `exs` files. This is my first time playing with Elixir. Thanks for such a thorough response, you're awesome :)
