### ISSUE TITLE
Can't select SDK on Windows 10

### ISSUE THREAD

**Issue by fuyutsuki** [KronicDeth/intellij-elixir#1080]
![image](https://user-images.githubusercontent.com/16377174/38788871-6f22280e-4171-11e8-9cd3-2d98bd42d666.png)

### Environments
- Win10Home (x64)
- Intelij Ultimate 2018.1
- Elixir 1.6.4
- Erlang/OTP20 [erts-9.2]

**Comment by KronicDeth** [comment]
The picture shows you selecting the bin directory, the SDK home is the
common ancestor of both the binaries like iex and mix and the lib .beam
files.  It should work if you select the Elixir directory, not the bin
directory.

**Comment by fuyutsuki** [comment]
Dear @KronicDeth.
No, this does not work even if Elixir directory is chosen.

**Comment by onethawt** [comment]
I'm encountering the same issue on Ubuntu 17.10. 

![image](https://user-images.githubusercontent.com/14185578/39194047-cfcf5ca0-47aa-11e8-948f-bb1c4e064f4f.png)

**Comment by KronicDeth** [comment]
@onethawt and @crertel,  you each are using different package managers and neither is using Windows 10 the way @fuyutsuki is.  This issue does not apply to you, open a different issue.

**Comment by KronicDeth** [comment]
@fuyutsuki how did you install Erlang and Elixir?

**Comment by fuyutsuki** [comment]
@KronicDeth I download and install by use installer from [here](https://elixir-lang.org/install.html#windows)

**Comment by onethawt** [comment]
@KronicDeth I installed Win 10 in a VM and got the same issue. I'll take a look at how the SDK detection is done because it seems off. 

I'm not sure what OS/Package Manager has to do with it as of yet.

**Comment by leggebroten** [comment]
I'm running Window 10 Pro.  
And like KronicDeth said you have to select the root Elixir directory.
![setting elixir sdk windows 10](https://user-images.githubusercontent.com/5223530/41502646-fb1f8a1a-717b-11e8-96b7-fd2137102c75.png)

**Comment by smeevil** [comment]
Hi,

So when using the windows installer of Elixir, I can select the Erlang and Elixir SDKS from `C:\Program Files\erl10.0.1` and `C:\Program Files (x86)\Elixir` with out a problem. However I use my complete dev environment in WSL (Ubuntu) while having the source on the windows side at `C:\User\smeevil\dev\elixir\<PROJECT>`. This works quite ok except that I cannot run the tasks from IntelliJ because it wants to use the windows side of erlang and elixir. 

If I point to erlang SDK to `C:\Users\smeevil\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\home\smeevil\.kerl\builds\21.0\release_21.0` It tells me that it's not a valid directory, however if I add the Elixir SDK with the path `C:\Users\smeevil\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\home\smeevil\.kiex\builds\elixir-git` it does except that without a problem. Though when trying to run tests from within IntelliJ it will still use the windows side of the erlang sdk…

Not sure how to solve this, but hope it helps with getting more insight :)

**Comment by KronicDeth** [comment]
@smeevil Open a separate issue for WSL SDK support

**Comment by Ox90** [comment]
Hey any advice on how to fix this?

**Comment by Ox90** [comment]
Ok i got it, you need select firts the path for erl and next the path for elixir... thats all...

**Comment by fuyutsuki** [comment]
@Ox90 I'll try it later, thx :)
