### ISSUE TITLE
Missing `:` or new line

### ISSUE THREAD

**Issue by santiagopoli** [KronicDeth/intellij-elixir#123]
Hi,
I've recently installed the plugin and I'm seeing these errors even in a simple elixir file like this:

![screenshot from 2015-05-07 10 44 51](https://cloud.githubusercontent.com/assets/759695/7516505/44371610-f4a6-11e4-9740-375659060567.png)
![screenshot from 2015-05-07 10 45 08](https://cloud.githubusercontent.com/assets/759695/7516507/44e42b16-f4a6-11e4-95f2-437687c33c42.png)

What am I doing wrong?

Thanks!

**Comment by KronicDeth** [comment]
Thanks for posting screenshots here on Github where other users can see them later if they have similar problems.

You aren't doing anything wrong. As the [README.md](https://github.com/KronicDeth/intellij-elixir/blob/481d04430c9be047523c807018181f7697c3de82/README.md):

> The parser is incomplete until v1.0.0. If you see an odd error from valid Elixir code, it is most likely due   to the incomplete parser. Please subscribe to notifications or comment on Issue #6 if you want to be notified when the parser is complete.

`Test do` is red because do block parsing is not yet implemented, so the parts of the parser that are implemented match what they can, the `defmodule`, and then the rest `Test do` is parsed as an adjacent expression, which triggers the message that there is a missing `;` or new line.

The big long error message is because the parser spits out all the possible token you could add at that point to make it not error after `end`.  I'm not entirely sure how to make the errors prettier although I can override more of the token names so it would say "&&, &&& or and" instead of AND_OPERATOR.  The "Missing `:` or new line" is only well formed because it's from an inspection I manually wrote instead of the automatic error message from the parser in the second screenshot.

Both error message are duplicates of #6, so click Subscribe on the Notification link on that issue or comment on it to be automatically subscribed to updates when the parser is complete.  You can either keep using the plugin in it's pre-1.0.0 state or wait until 1.0.0 is released.  I appreciate any testing you do do pre-1.0.0 as other users have caught bugs that weren't due to parser incompleteness before.

Thanks for your bug report.
