### ISSUE TITLE
[RubyMine + Elixir] "Elixir Facet SDK is not defined" message won't go away

### ISSUE THREAD

**Issue by ryancammer** [KronicDeth/intellij-elixir#1232]
Even after uninstalling Elixir, Erlang, the plugin, and restarting the IDE, the banner prompting me to "Setup Elixir Facet SDK" won't go away in Ubuntu 18.04. As far as I can tell, everything is set up the way it should be set up.

![screenshot from 2018-08-24 11-53-53](https://user-images.githubusercontent.com/376128/44602462-8dc07980-a794-11e8-8619-d666c14d6804.png)
![screenshot from 2018-08-24 11-54-07](https://user-images.githubusercontent.com/376128/44602468-9022d380-a794-11e8-9a8e-44ef416f9105.png)

**Comment by KronicDeth** [comment]
If you can see Languages & Frameworks > Elixir you haven't uninstalled the plugin.

**Comment by KronicDeth** [comment]
Assuming you meant to say "installing", the issue is that you have defined the SDK in the application-wide setting, but not said that the SDK is for this specific project.

By JetBrains convention, in the single-language IDEs, application-wide configuration has no annotation, while project-specific configuration has "For current project" and the layered files icon.  

* Languages & Frameworks > Elixir > SDKs has neither the icon or the annotation, so that means it is an application-wide setting.
* Languages & Frameworks > Elixir has the icon and "For current project", so it is where you set the SDK for the project you currently have open.

![screen shot 2018-08-25 at 3 22 44 pm](https://user-images.githubusercontent.com/298259/44622309-a6578f00-a87b-11e8-8e32-fbbf4fbcd823.png)

![screen shot 2018-08-25 at 3 22 57 pm](https://user-images.githubusercontent.com/298259/44622312-aa83ac80-a87b-11e8-929e-650114e35a1a.png)

I'm sorry if you find this confusing, but it is a side-effect of the conventions in the single-language IDEs that JetBrains has established.  Project vs Application-wide settings are more separated in IntelliJ IDEA which supports multiple languages because the section is labeled "Platform Settings" for application-wide and "Project Settings" for project-specific settings

![screen shot 2018-08-25 at 3 30 47 pm](https://user-images.githubusercontent.com/298259/44622336-fa627380-a87b-11e8-988a-c18f61748764.png)

If you're using Elixir a lot and not using your other languages in the same project you may find it easier to use IntelliJ IDEA Community Edition (which is free) or IntelliJ IDEA Ultimate Edition (which is subscription-based like the single-language IDEs) as either version of IDEA makes using other languages easier than the Facet system I have to use to allow you to set Elixir SDKs in the single-language IDEs.  The Facet system means that your IDE still thinks the project is a Ruby project in Rubymine or a PHP project in PHPStorm, so if your project is only Elixir, it can be better represented in IntelliJ IDEA, which doesn't require the root Project to be Java-based.

**Comment by ryancammer** [comment]
You're right, I totally missed the "For current project" text there, but by clicking on 'Setup Elixir Facet SDK' it took me to the SDKs menu rather than the 'For current project' setting.

But I think you're also right, in that it's time to just switch to Idea.

**Comment by ryancammer** [comment]
Also, thanks again for all of the work you put into this!

**Comment by PabloHdzVizcarra** [comment]
thanks friend for explaining things i was in the same problem, now we are going to install intellij
