### ISSUE TITLE
Creating New File after "New Project" creation, is not possible due to filename not valid

### ISSUE THREAD

**Issue by jjoselv** [KronicDeth/intellij-elixir#139]
After I create a New Elixir Project, and I click on "New"->"Elixir File", I cannot create a new Elixir file - any name that I put doesn't match the pattern for the filename. On top of that, the title of the window when creating a new file is: "New Elixir Module":

![Image of error](http://i60.tinypic.com/2enypvc.png)

Is this going wrong?

Tested on IntelliJ IDEA 14.1.4, Windows 7 - x32

**Comment by KronicDeth** [comment]
The New Elixir dialog

![screen shot 2015-06-23 at 9 14 49 pm](https://cloud.githubusercontent.com/assets/298259/8321482/f837a268-19ec-11e5-84fe-8a566cb2db48.png)

assumes the name follows Elixir module naming conventions, so you'd have use a valid Alias name like `Foo.Bar` or `Elixir.File`.  You don't include the `.ex` or `.exs` extension.

If you want to not have intellij-elixir automatically create the containing directories (`Foo.Bar` will be created in `foo/bar.ex`) or you want to control the extension, then use the normal New File dialog that isn't language specific and you can specify the extension.

![screen shot 2015-06-23 at 9 14 13 pm](https://cloud.githubusercontent.com/assets/298259/8321468/da3dce90-19ec-11e5-8332-19f102eabe3f.png)


  It is actually the extension being `.ex` or `.exs` that triggers the Elixir icon and the parser knowing it's Elixir.  You don't have to use the New Elixir.

I haven't opened an issue for this yet, but I plan to expand the New Elixir dialog so you can override the path creation as Phoenix doesn't use the app namespace in the paths (i.e. `MyApp.User` is in `web/models/user.ex` instead of `web/models/my_app/user.ex`).  If you can describe a use case or how you'd like the dialog to work I can add that as a feature request (this is a bug issue right now).

If my explanation addresses your issue please close this issue.

**Comment by jjoselv** [comment]
Oh, my bad man, I misunderstood the thing about Elixir files and Elixir modules. No probs! And very good job! ^^
