### ISSUE TITLE
Jump to deps modules with ctrl+click

### ISSUE THREAD

**Issue by JerryBels** [KronicDeth/intellij-elixir#1398]
Hello,

Currently when you want to see deps code to check how a given library handles things, you got to search for it manually.

I want to index deps code, such as when I ctrl+click a module / function from a dep I get taken there directly, like my own code.

**Comment by KronicDeth** [comment]
That works and has worked for a long time.  Before `v10.0.0`, the `deps` directory wasn't marked as Excluded and all deps were indexed as part of the project.  Afer v10.0.0` `deps` were added as External Libraries.

Here's how it looks in an umbrella project for `v10.2.0`.

I can Cmd+Click (macOS version of Ctrl+Click) on `from` that is imported from `Ecto.Query` and it shows the ability to jump to the near `import` or the actual definition in the dep:

![screen shot 2019-02-21 at 7 39 19 am](https://user-images.githubusercontent.com/298259/53172936-2ac96700-35ac-11e9-865b-475cf85f0155.png)

If I select the definition it jumps there.

![screen shot 2019-02-21 at 7 39 26 am](https://user-images.githubusercontent.com/298259/53172993-58161500-35ac-11e9-99f0-e18ab2c9b610.png)

The `deps` director because it represents external libraries is marked as ignored

![screen shot 2019-02-21 at 7 39 44 am](https://user-images.githubusercontent.com/298259/53173063-80057880-35ac-11e9-9fcf-bad20143092c.png)

But, they are still indexed because they're registered (automatically by Virtual Filesystem water) as External Libraries.

![screen shot 2019-02-21 at 7 40 23 am](https://user-images.githubusercontent.com/298259/53173236-e094b580-35ac-11e9-8034-a724203eddab.png)

Those libraries are then attached as Dependencies to the Modules.  This is done with another watcher that interprets the `mix.exs` `deps` function.

![screen shot 2019-02-21 at 7 40 38 am](https://user-images.githubusercontent.com/298259/53173293-fe621a80-35ac-11e9-8554-2e959829cb0a.png)

These screenshots are from IntelliJ IDEA Ultimate, but it would look the same in IntellIJ IDEA Community Edition.  For single-language IDEs the view is different because they hide the Module system and only allow 1 Module per Project, so umbrellas end up as multi-project instead.

Which IDE are you using?  If you want to show me what you're seeing we can setup a Zoom video chat.  Just email at the address on my GitHub profile.

**Comment by JerryBels** [comment]
Hey man :)

Actually it does work in some projects - the older ones, I can get to whatever function I want in deps. Which makes me guess it might be related to this issue : https://github.com/KronicDeth/intellij-elixir/issues/1378

On older projects, I have the SDK defined correctly. Everything works as expected (and as I was remembering it should).

On new projects, it doesn't work at all until I try the hack offered by Mike on the linked topic, and then it does work partially - native Elixir features opens, but deps won't. Which seems related to them not getting the SDK correctly defined.

I'm on PHPStorm ATM. Would you recommend trying out IDEA Community Edition ?

**Comment by KronicDeth** [comment]
> I'm on PHPStorm ATM. Would you recommend trying out IDEA Community Edition ?

Yes, if you can use IntelliJ it will be a better experience.  IntelliJ supports multi-modules and external dependency management while support in the single-language IDEs is me backporting features, so it is more likely to be buggy as #1378 shows.

**Comment by JerryBels** [comment]
Okay, looks like community edition is perfect for Elixir... Does the Ultimate Edition gives you more for Elixir programming specifically ? 

Anyways, closing this now as the real bug is #1378
