### ISSUE TITLE
Performance issues while typing

### ISSUE THREAD

**Issue by wdavies973** [KronicDeth/intellij-elixir#1400]
I'm running InteliJ on 2019.3.4 with intelij-elixir plugin v10.2.0.
I'm experiencing lag related to typing, essentially, whenever I type anything, the editor will freeze after about 5 characters for a few seconds, and then continue for 5 characters, freeze, etc.

I've disabled credo and all other Elixir inspections. Memory usage doesn't seem to jump about 200 MB ever. Just recently re-installed Windows 10. Disabled almost all the plugins to no avail. The same version of InteliJ works fine on a Ubuntu boot running off the same hardware.

Let me know what more information you need to diagnose the issue more thoroughly.

**Comment by smeevil** [comment]
On one of my bigger projects, I run into the exact same problem. IntelliJ 2018.3.4 with plugin 10.2.0.
It freezes according to the dumps anywhere between 7 to 31 seconds.
I've attached a bunch of treadDump-freezeses from the past two days, hope this helps you with locating the problem because this is quite annoying. And if there is anything I can do to provide more information, please do let me know :)

[Archive.zip](https://github.com/KronicDeth/intellij-elixir/files/2904970/Archive.zip)

**Comment by KronicDeth** [comment]
@smeevil all your threads look like they're in a part that is checking the version of Elixir to determine which version of the grammar to support.  Your SDK works for running `mix test` Run Configurations, right?  If not, it could be something pathologic about the caching when the Elixir version can't be determined.

**Comment by smeevil** [comment]
Running the tests inside intelliJ works fine indeed

**Comment by KronicDeth** [comment]
What version of Elixir and Erlang are you using, including the installation tool for each?

**Comment by smeevil** [comment]
```
elixir --version
Erlang/OTP 21 [erts-10.0.5] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.7.2 (compiled with Erlang/OTP 21)
```

<img width="736" alt="screenshot 2019-02-26 at 18 11 10" src="https://user-images.githubusercontent.com/13874/53432103-2d83ec00-39f2-11e9-9f6f-ceab6ba8f8f6.png">
<img width="536" alt="screenshot 2019-02-26 at 18 10 10" src="https://user-images.githubusercontent.com/13874/53432104-2d83ec00-39f2-11e9-9169-901cfd8ff197.png">

I do notice just now, about that unknown elixir version.... might that be the problem ?

**Comment by smeevil** [comment]
Oh And installed by brew

**Comment by wdavies973** [comment]
I can confirm the issue with the plugin not knowing which version of Elixir is correct.

**Comment by smeevil** [comment]
I've updated Elixir 1.8.1, Erlang 21.2.4, IntelliJ 2018.3.5.
Updated the project preferences so it only references the correct version.

Alas this still results in the same issue.
<img width="1107" alt="screenshot 2019-02-27 at 14 24 55" src="https://user-images.githubusercontent.com/13874/53493393-89ef1600-3a9b-11e9-8cb2-c50ec8963bfe.png">

**Comment by smeevil** [comment]
Is there anything I can do to help expedite this issue ? Trying not to stab my eye out with a fork and had to switch to vscode for now.

**Comment by smeevil** [comment]
Sorry, frustration took over :/ I don't want to be an arse about it! Do let me know though if there is anything I can provide to figure out what might be causing this :)

**Comment by KronicDeth** [comment]
@smeevil are you able to build the plugin on your own?  If you can then there's some code deletions we could try locally for you.

**Comment by smeevil** [comment]
Apparently I can :)
<img width="449" alt="screenshot 2019-03-05 at 18 59 07" src="https://user-images.githubusercontent.com/13874/53826416-d85b5380-3f78-11e9-9468-82a8701f23ee.png">

**Comment by KronicDeth** [comment]
@smeevil try 
[intellij-elixir-10.3.0-pre+20190305190822.zip](https://github.com/KronicDeth/intellij-elixir/files/2932414/intellij-elixir-10.3.0-pre%2B20190305190822.zip)

It ensures that the LevelPropertyPusher cache is being used more often.  Let me know if it works and I'll open a PR.

**Comment by smeevil** [comment]
Thank you so much for your time ! 
I'll let you know tomorrow after I've had some time working with it.

**Comment by smeevil** [comment]
Most of today was spend in Typescript, so I had some limited time to check out the results in the Elixir code. But initial impressions seems good, one thing that is especially noticeable is the increase in speed of syntax highlighting, which now starts immediately when opening a new file.

I'll report back tomorrow :)

**Comment by smeevil** [comment]
@KronicDeth I'v spend the majority of the day writing type specs in Elixir today, and it seems the problem is indeed gone \o/ It feels as smooth as ever now :)

**Comment by KronicDeth** [comment]
Ok, that means that this bug was potentially introduced as earlier as[v7.0.0]() (2017-12-15) and as late as [v7.5.0](https://github.com/KronicDeth/intellij-elixir/releases/tag/v7.5.0) (2018-06-03) as that's [the history for `LevelPropertyPusher.java`](https://github.com/KronicDeth/intellij-elixir/commits/da149f8430cd378e964ae5a53a127754b3a00bc9/src/org/elixir_lang/file/LevelPropertyPusher.java) and has affected all later versions.  Someone came up to me at ElixirConf US and said the 6 series was faster, so this could be why.  I had assumed it was some other feature I added in the 7 series doing it at the time.

I'm going to add information about how to report performance issues with the thread dumps to the readme and issues template and then include those in the release blog post on the DockYard blog, so that hopefully others can repeat what you did @smeevil in the future.

**Comment by smeevil** [comment]
Quite amazing that nobody else really ran into this issue though o.O
Anyways super happy that this has been resolved, thank you so much !

**Comment by KronicDeth** [comment]
@smeevil I think people have run into the issues, but all I can do is 🤷‍♂️ when someone reports general performance issues since it usually involves large private repos.  The thread dumps is the first thing that worked to find one of these bugs without an Elixir reproduction repo.

**Comment by wdavies973** [comment]
Issues are fixed for me as well, thanks!
