### ISSUE TITLE
Module attribute falsely flagged as 'Unresolved module attribute'

### ISSUE THREAD

**Issue by rengel-de** [KronicDeth/intellij-elixir#1767]
```elixir
defmodule Calixir.Calendar.Hebrew do
  @nisan 1
  @iyyar 2
  @Sivan 3
  @tammuz 4
  @av 5
  @elul 6
  @tishri 7
  @marheshvan 8
  @kislev 9
  @tevet 10
  @shevat 11
  @adar 12 # This one creates an error.
  @adarii 13

  def nisan, do: @nisan
  def iyyar, do: @iyyar
  def sivan, do: @Sivan
  def tammuz, do: @tammuz
  def av, do: @av
  def elul, do: @elul
  def tishri, do: @tishri
  def marheshvan, do: @marheshvan
  def kislev, do: @kislev
  def tevet, do: @tevet
  def shevat, do: @shevat
  def adar, do: @adar  # Falsely flagged as 'Unresolved module attibute'.
  def adarii, do: @adarii
end
```

If two module attributes start with the same letters (like `@adar` and `@adarii` in the code above), then later in the code, the shorter one is falsely flagged as an 'Unresolved module attribute'.

**Comment by KronicDeth** [comment]
It is probably due to when I relaxed the references implementation to support Go To Definition and Show Info when typing and it broke an assumption in the module attribute annotator because it assumes there must be exactly one resolution instead of checking that there is 1 valid match.  (Partial matches aren't marked as valid.)

**Comment by rengel-de** [comment]
Thanks! Problem is gone.
