### ISSUE TITLE
Seperate keywords, variables and function for syntax highlighting

### ISSUE THREAD

**Issue by plamb** [KronicDeth/intellij-elixir#179]
Quick suggestion, no idea if this is actually possible. 

I'd love to see the identifiers category split up into separate ones for keywords, variables and function names. And to go even further, it would be amazing if there was a way to visually group function names that are the same but have different pattern matched arguments (maybe have a background color that changes).

**Comment by KronicDeth** [comment]
I can't do the basic-level syntax highlighting like the current categories that would distinguishes between keywords, variables, and functions because that highlighting is attached to the ASTNodes that the lexer produces and they are all IDENTIFIER tokens at that level.  I can use the annotates to do highlighting at the higher parser level though, but I haven't done anything like that yet.  I'm working through the first annotator example #84 right now.  Once I understand how the highlighting works with the annotators I should be able to do this.

**Comment by zyuyou** [comment]
@KronicDeth , maybe you can see [ErlangAnnotator](https://github.com/ignatov/intellij-erlang/blob/master/src/org/intellij/erlang/editor/ErlangAnnotator.java).

**Comment by supersasha** [comment]
Can you separate such macros identifiers like `def`, `defp`, `defmodule`, `defmacro`, `if`, `case` etc. by just enumerating and hard-code them? I mean not using AST, just dummy comparison of identifiers (produced with AST) with the list of keywords. It is very hard to read code where such key macro identifiers not separated from the rest of identifiers. Later you'll still be able to change this solution to a more appropriate one.

**Comment by KronicDeth** [comment]
@supersasha I'm going to make an Annotator that covers the standard library macros like `def`, `alias`, and `defmacro` and a separate Annotator for ExUnit since Rubymine has a special annotator for the testing DSLs like `it` and `should` in RSpec.

**Comment by KronicDeth** [comment]
Just found out it **is** possible to set the attributes for the custom `TextAttributeKey`s using an `additionTextAttributes` key, which would allow to set the attributes in the default theme or Darcula.  That is now open as #299

**Comment by KronicDeth** [comment]
#314 added syntax highlighting for Parameters, Ignored Variables, and Variables.

**Comment by KronicDeth** [comment]
#452 added support for highlighting function calls when the references resolve, specifically 8ef62c4bc
