### ISSUE TITLE
default SDK path on Windows

### ISSUE THREAD

**Issue by hivre** [KronicDeth/intellij-elixir#182]
The default SDK path on Windows 7 is `C:\Program Files (x86)\Elixir\bin`, if all defaults in the elixir installer are followed.

![windows_elixir](https://cloud.githubusercontent.com/assets/9581049/9055450/820796a6-3a8b-11e5-9985-0e82eb05743e.png)

**Comment by f-lombardo** [comment]
I tried to import a mix project setting the above (correct) path, but the import wizard seems not to see mix.   Is it due to the fact that the mix "executable" is mix.bat instead of mix? I use Elixir 1.1.0 intellij idea 15.0.1 and the 1.2.1 version of the plugin.
Thanks
![mix](https://cloud.githubusercontent.com/assets/280709/11613072/1cef4a8a-9c14-11e5-9f56-aaace52bbd12.PNG)

**Comment by zyuyou** [comment]
@f-lombardo You are right, the mix "executable" is mix.bat on Windows. Maybe you need to set the `mix.bat` path manually.

**Comment by cdegroot** [comment]
Can confirm both the default path (on Win10 too) and the fact that you can't get beyond the step that @f-lombardo posted. I tried a handful of variations (point to the Elixir dir, to bin/, to bin/mix, bin/mix.bat, even lib/mix), to no avail. Version stays on N/A and Next button doesn't work.

**Comment by f-lombardo** [comment]
A simple work around is changing mix.bat this way
`@echo off
rem if "%1"=="--version" echo Mix 1.1.1
call "%~dp0\elixir.bat" -e Mix.start -e Mix.CLI.main %*`

**Comment by zyuyou** [comment]
@cdegroot this problem will be fixed in the #220

**Comment by cdegroot** [comment]
@zyuyou That's great news. I'm not developing often on Windows, but yell if I need to test/verify stuff.

**Comment by KronicDeth** [comment]
This should have been closed by #188, but github didn't recognize @zyuyou's phrasing, so closing manually.
