### ISSUE TITLE
Automatic tabbing on invalid syntax

### ISSUE THREAD

**Issue by D4no0** [KronicDeth/intellij-elixir#1825]
When making some syntax that is not valid, when moving code to a new line, tabs are applied automatically, this is really irritating when you want to write multi-line functions.
Example:
![image](https://user-images.githubusercontent.com/22370804/93842785-ac114000-fca0-11ea-90c7-a3f493015bd5.png)

![image](https://user-images.githubusercontent.com/22370804/93842819-c0553d00-fca0-11ea-88a3-d6e9e4212fca.png)

**Comment by KronicDeth** [comment]
This isn't a thing I control on a per-language level (as far as I know).  Similar things happen with the Rust plugin too and it happens to be in YAML files too.  Since the YAML support is something written by JetBrains itself, I don't think the Paste system and formatting system takes into account whether the syntax is valid or not.

You probably want to use "Paste without Formatting", you can do this in the menu from Edit > Paste > Paste Without Formatting or the keyboard shortcut is Opt+Shift+Cmd+V on macOS.  Not sure what it is on Linux or macOS.

**Comment by D4no0** [comment]
Wow, now this is quite interesting information. I never noticed this to happen with their official languages.
