### ISSUE TITLE
html.leex doesn't indexing HTML

### ISSUE THREAD

**Issue by DevWasi** [KronicDeth/intellij-elixir#1869]
**Describe the bug**
Previous version of Elixir Plugin 10.8.1 was working perfectly with Live Templates, After i upgraded to 11.9.0 it doesn't work with HTML. 

**Expected behavior**
Just like the previous version of Elixir Plugin, 

**Screenshots**
<img width="837" alt="Screen Shot 2021-01-09 at 4 50 44 PM" src="https://user-images.githubusercontent.com/48654021/104090785-d95b1b80-529a-11eb-900d-d983c64bdfc5.png">

**Logs**
If reporting a hang or other performance issue, please attach the [thread dumps](https://intellij-support.jetbrains.com/hc/en-us/articles/206544899-Getting-a-thread-dump-when-IDE-hangs-and-doesn-t-respond).

**Desktop:**
 - OS: [e.g. macOS]
 - Version [e.g. 11.1 and 10.15.7]
 -
**Plugin:**
- Version [e.g. 11.9.0]

**Comment by ruudk** [comment]
Same issue here. It stopped working.

**Comment by ruudk** [comment]
This solves the problem 🎉 
![Screenshot 2021-01-15 at 12 44 06@2x](https://user-images.githubusercontent.com/104180/104723421-83212900-572f-11eb-9e7d-e5620b774f74.png)

**Comment by KronicDeth** [comment]
@ruudk while that works you've now made all `*.leex` files think they are HTML even if you do `foo.xml.leex` or `foo.svg.leex`.  

The code as written is supposed to derive the Template data language from the extension before the `.leex`, so when it is `.html.leex` it will take the `html` and look it up at runtime, this way, other plugins can add new extensions and you're always able to make `.eex` and `.leex` versions of those files.

This bug is like due to the change from `fileTypeFactory` to `fileType` extension for the 2020 releases of the IDEs.

**Comment by KronicDeth** [comment]
Try out [intellij-elixir-11.9.3-pre+20210124050607.zip](https://github.com/KronicDeth/intellij-elixir/files/5861607/intellij-elixir-11.9.3-pre%2B20210124050607.zip) to see the fix.

**Comment by ruudk** [comment]
@KronicDeth Thanks! I installed the .zip and it works even when reverting my "hack" (I only use HTML LEEX anyway). 

Would be good to release+tag!
