### ISSUE TITLE
AssertionError in ElixirPsiImplUtil.operator(Infix) when error in infix operation

### ISSUE THREAD

**Issue by wanderanimrod** [KronicDeth/intellij-elixir#251]
<img width="945" alt="screen shot 2016-03-10 at 3 25 25 pm" src="https://cloud.githubusercontent.com/assets/3718698/13683408/83f7b9e6-e6d4-11e5-935c-b5a8780ae1d3.png">

The IDE doesn't allow me to submit the error, perhaps because the error message is null.

**Comment by KronicDeth** [comment]
Do you have a code sample that triggered the error?  I can't off the top of my head think of how an operation would have a null operator.  Maybe how I handle guards for stab clauses like in anonymous functions?  Sample code would help a lot.

**Comment by wanderanimrod** [comment]
<img width="867" alt="screen shot 2016-03-10 at 9 14 16 pm" src="https://cloud.githubusercontent.com/assets/3718698/13691224/18114b3a-e705-11e5-9614-cd098f05bbeb.png">

You notice there is a syntax error on the second line (an unclosed square bracket). Having the code looking like that raises the same error every time you change any other part of the file, without the IDE ever getting out of the "Performing code analysis" state.  At some point, the plugin crushes and the IDE asks if I want to disable it.

**Comment by KronicDeth** [comment]
Maybe there's someway to detect when an element has a parse error and then turn off the higher-level functions like annotator.  I'll have to look through the available methods on all the interfaces.

**Comment by wanderanimrod** [comment]
Alright. Thanks.

**Comment by KronicDeth** [comment]
Ok, I can trigger it when typing the second line.  It is that the operation has only 2 children instead of the expected 3:

![screen shot 2016-03-18 at 9 43 03 pm](https://cloud.githubusercontent.com/assets/298259/13896221/7d8feb08-ed52-11e5-8e79-fc6423b153b3.png)

This is definitely caused by the automatic error handling that GrammarKit adds when triggering the Pratt Parser generation: as long as the operator of a binary operation matches, it doesn't matter if the right operand is missing.  This likely could affect other places beside `operator` since I assert on the children length a lot to ensure I'm not assuming a structure that's no longer valid for the grammar rules matching the method.  I still need to figure out if I can consistently tell there is an error, otherwise, I'll just relax the restriction to `>= 2` and assume the `[1]` is the operator.
