### ISSUE TITLE
Syntax highlighting function calls

### ISSUE THREAD

**Issue by smeevil** [KronicDeth/intellij-elixir#261]
Hi,

I was wondering what I'm doing wrong since my function calls are not syntax highlighted.
I'm read in the release notes that it uses the fallback of function call in the general settings, which I did update.

This is a screenshot of the default settings : 

![defaults](https://dl.dropboxusercontent.com/s/cz07q3lp19p048n/2016-03-20%20at%2014.49.png)

and this is how my elixir code looks like :

![code](https://dl.dropboxusercontent.com/s/stw5cfzhchh6vi2/2016-03-20%20at%2014.48.png)

I'm using version 2.2 of the intellij-elixir plugin and darcula theme.

Gerard.

**Comment by smeevil** [comment]
This seems related to #250, as I'm running IntelliJ Ultimate 2016.1
If so, you can close this one :)

**Comment by KronicDeth** [comment]
I may have phrased the release notes poorly: it's not that *all* function calls are highlighted, it's that functions and macros from `Kernel` [functions](http://elixir-lang.org/docs/stable/elixir/Kernel.html#functions) and [macros](http://elixir-lang.org/docs/stable/elixir/Kernel.html#macros) and `Kernel.SpecialForms` [macros](http://elixir-lang.org/docs/stable/elixir/Kernel.SpecialForms.html#macros) use the color of Function Call as parent `TextAttributesKey`, so that they can inherit those settings from themes like Darcula.

```java
    public static final TextAttributesKey KERNEL_FUNCTION = createTextAttributesKey(
            "ELIXIR_KERNEL_FUNCTION",
            DefaultLanguageHighlighterColors.FUNCTION_CALL
    );

    public static final TextAttributesKey KERNEL_MACRO = createTextAttributesKey(
            "ELIXIR_KERNEL_MACRO",
            DefaultLanguageHighlighterColors.FUNCTION_CALL
    );

    public static final TextAttributesKey KERNEL_SPECIAL_FORMS_MACRO = createTextAttributesKey(
            "ELIXIR_KERNEL_SPECIAL_FORMS_MACRO",
            KERNEL_MACRO
    );
```
-- [`org.elixir_lang.ElixirSyntaxHighlighter.java`](https://github.com/KronicDeth/intellij-elixir/blob/v2.2.0/src/org/elixir_lang/ElixirSyntaxHighlighter.java#L81-L94)

(It is possible to not inherit from a pre-existing `TextAttributesKey`, but then you have to always manually configure it unless themes start supporting your custom key.)

**It is working because your `def`, `is_atom`, `is_integer`, `to_string`, `is_binary`, `case` are all purple**.

The settings for those are all in Preferences > Editor > Color & Fonts > Elixir.

![screen shot 2016-03-20 at 10 52 42 am](https://cloud.githubusercontent.com/assets/298259/13905318/857e1216-ee8a-11e5-8d4f-7accca531e91.png)

Change those settings instead of Preferences > Editor > Color & Fonts > Language Defaults > Identifiers > Function Calls.

![screen shot 2016-03-20 at 11 00 00 am](https://cloud.githubusercontent.com/assets/298259/13905330/ee82331e-ee8a-11e5-8264-31020a622fd8.png)

#250 is referring to Module Attribute, Specification, Type, and Type Parameter all showing `__deprecated__` for their base `TextAttributeKey`, which doesn't affect Kernel Function, Kernel Macro, or Kernel Special Forms Macro

![screen shot 2016-03-20 at 11 03 26 am](https://cloud.githubusercontent.com/assets/298259/13905353/76197120-ee8b-11e5-882e-d0eb2fa73677.png)
