### ISSUE TITLE
Intellij freezes

### ISSUE THREAD

**Issue by l-ray** [KronicDeth/intellij-elixir#2758]
Intellij stopps being responsive in arbitrary situations, which can be reproduced - e.g. on changing a pipe command on a different line. 
Only way to recover is a `pkill -9 java` and restart of IntelliJ.

**Logs**
Please find attached a zip with logs from frozen situations.
[threadDumps-freeze-20220725-1.zip](https://github.com/KronicDeth/intellij-elixir/files/9189183/threadDumps-freeze-20220725-1.zip)

**Desktop:**
 - OS: Fedora
 - Version 36
 - IntelliJ Build #IC-221.6008.13, built on July 19, 2022

**Erlang:**
- Installer ASDF
- Version 24.3.4

**Elixir:**
- Installer ASDF
- Version 1.13.4-otp-24

**Plugin:**
- Version 13.1.1

**Additional context**
Overall a really impressive plugin - thank you so much. Please contact me if I can help somehow.

**Comment by KronicDeth** [comment]
It looks like the threads are unrelated to your change to the pipe command.  Instead the common point is 

```
at org.elixir_lang.beam.psi.BeamFileImpl.setMirror(BeamFileImpl.kt:407)
```

so, the parsing of decompiled Beam source.  In #2800, the logging of which file is problematic is improved and the Elixir function bodies are truncated for large functions, which improved the performance of the decompiler.  It is likely this bug is fixed by #2800, which was released in 13.2.1
