### ISSUE TITLE
org.elixir_lang.sdk.erlang_dependent.MissingErlangSdk: Elixir SDK `Elixir 1.14.0` is missing Erlang SDK at org.elixir_lang.Elixir.elixirSdkToEnsuredErlangSdk(Elixir.kt:35)

### ISSUE THREAD

**Issue by FreekVanDooren** [KronicDeth/intellij-elixir#2895]
# System

Plugin Version: 13.2.1
Application: IntelliJ IDEA Ultimate Edition (2022.2.2)
Operating System: Mac OS X (12.6)

# Event

### Stacktrace

<details>

<summary>
org.elixir_lang.sdk.erlang_dependent.MissingErlangSdk: Elixir SDK `Elixir 1.14.0` is missing Erlang SDK
</summary>

```
org.elixir_lang.sdk.erlang_dependent.MissingErlangSdk: Elixir SDK `Elixir 1.14.0` is missing Erlang SDK
	at org.elixir_lang.Elixir.elixirSdkToEnsuredErlangSdk(Elixir.kt:35)
	at org.elixir_lang.Elixir.commandLine(Elixir.kt:19)
	at org.elixir_lang.Mix.commandLine(Mix.kt:19)
	at org.elixir_lang.mix.project._import.step.Root$1.run(Root.java:80)
```

</details>

## User perception
Trying to setup this Elixir plugin. I installed Elixir using homebrew. This plugin/IntelliJ seems to have trouble picking up it's installation folder. I somehow mangled it to recognize where the Elixir SDK is installed (`/opt/homebrew/bin/elixir/Cellar/elixir/1.14.0`) thanks to [this walkthrough](https://github.com/KronicDeth/intellij-elixir#small-ides) (which I shouldn't need 🤷) , but now it's missing Erlang... I'm at a loss how to set that up.
Not sure if this is significant, but neither Elixir nor Erlang are showing up under "Languages & Frameworks" in my preferences view.
<img width="235" alt="image" src="https://user-images.githubusercontent.com/14352428/194757183-dafef485-c04d-4db9-8aa7-32defdb367cb.png">

**Comment by KronicDeth** [comment]
SDK in IntelliJ (as opposed to the Small IDEs) are all managed by the Project Structure menu.  This is the same way you'd setup a JDK for Java.  It is not special to Elixir for IntelliJ.

There is no Elixir or Erlang entries under Languages & Frameworks because there are no settings that need customization there. That indicates nothing about whether the plugin is working.

The Elixir SDK asks you select the Erlang SDK if one is not already setup, but if you did not see thatit's a dropdown in the SDK setup.  I'll go through the steps

1. File > Project Structure
  ![Screen Shot 2022-10-28 at 3 22 07 PM](https://user-images.githubusercontent.com/298259/198725699-6b81a324-d528-4575-96b2-cff75ca8f78c.png)
2. Select SDKs.  Click +.  Click Add Erlang SDK for Elixir SDK
  ![Screen Shot 2022-10-28 at 3 24 18 PM](https://user-images.githubusercontent.com/298259/198726008-3eca9f60-b22a-4afc-a398-0b0e21436a47.png)
3. It will select what it thinks is the newest homebrew, ASDF, or Nix install, but you can change it.  Click Open to Select the folder.
   ![Screen Shot 2022-10-28 at 3 24 28 PM](https://user-images.githubusercontent.com/298259/198726015-865d4a5d-a357-4236-b472-d8889a3aa449.png)
4. Select SDKs.  Click +.  Click Add Elixir SDK
  ![Screen Shot 2022-10-28 at 3 22 22 PM](https://user-images.githubusercontent.com/298259/198725702-a9a39aa9-00b7-4d1e-a8ec-27936dd9796b.png)
5. It will select what it thinks is the newest homebrew, ASDF, or Nix install, but you can change it.  Click Open to Select the folder.
  ![Screen Shot 2022-10-28 at 3 22 32 PM](https://user-images.githubusercontent.com/298259/198725705-294dae6f-75f1-428c-8208-143fe2bc351f.png)
6. In the SDK menu click the Elixir SDK you created and make sure the Erlang SDK you created is selected
   ![Screen Shot 2022-10-28 at 3 22 42 PM](https://user-images.githubusercontent.com/298259/198725707-c644ef35-40b3-4715-b94d-b15bae80aeba.png)
7. Make sure the Elixir SDK is your current project SDK
  ![Screen Shot 2022-10-28 at 3 22 51 PM](https://user-images.githubusercontent.com/298259/198725709-05b677bd-6698-479d-afbd-3780640e4c46.png)

**Comment by FreekVanDooren** [comment]
@KronicDeth Thanks for making this step-by-step 🙏 . Worked perfectly (just not on EAP... but that's even less your problem)
