### ISSUE TITLE
Goto declaration not working / compilation completed with errors

### ISSUE THREAD

**Issue by andshape** [KronicDeth/intellij-elixir#307]
First of all, thanks for taking the time to create this plugin!

I am experiencing two problems with the plugin that I believe are related so I am posting this as one issue:

If I make the project (Ctrl+F9) from within IntelliJ I get the following error:
**Error: mix: syntax errro before: '('
Error: mix: Code.require_file/2**

(I does not mention a specific file or line number)

Furthermore, it is not possible for me to use the "find usages" navigation command (it says "cannot search for usages") or "go to declation" navigation command or "Quick documentation" (Ctrl+Q).

It is, however, possible for me to create an Elixir Mix configuration and compile through that (by putting "compile" as the command).

Under **Settings->Build, Execution, Deployment->Compiler->Elixir Compiler** I have the following checkboxes selected: "Compile project with mix", "Attach debug info".
I have tried deselecting "Compile project with mix" but that didn't make a difference.

Under **Settings->Other Setings->Elixir External Tools**  I have path=C:\Program Files (x86)\Elixir\bin\mix.bat  and version=1.2.4  

Under **Project Structure->Project Settings->Project** the Project SDK is set to Elixir 1.2.4  and Project Language level: SDK Default (1.3 - Plain old java). The Project language level looks wrong but I cannot set it to Elixir - is it ok?

Under **Project Structure->Project Settings->Modules** I have one module (an Elixir app using Phoenix). I have added the "web" folder as source folder (so my source folders are "lib" and "web"). 
Under paths I have "Use module compile output path", output path=[Path to project]_build\dev\lib[name of project]\ebin, test output path=[Path to project]_build\test\lib[name of project]\ebin  "Exclude output paths" is checked. Under dependencies I have Module SDK: Project SDK (Elixir 1.2.4) and in the list I have Elixir 1.2.4 and <Module source>.

Under *_Project Structure->Platform Settings-> SDKs *_I have Elixir 1.2.4.   Classpath = Sourcepath = C:\Program Files (x86)\Elixir\lib  and Documentation Paths = http://elixir-lang.org/docs/stable/elixir/

I am running on windows and I am using the community edition of IntelliJ and the Elixir plugin version is v3.0.1 (Installed via IntelliJ's plugin system).

**Comment by KronicDeth** [comment]
Do you remember how you setup the project?  Did you do [Import From External Model](https://github.com/KronicDeth/intellij-elixir#import-project-from-external-model)?  A lot of people don't have good luck using the non-Mix project types.

**Comment by andshape** [comment]
Yes, I did import from external model. Just to double check I just redid the import, but unfortunately is still doesn't work correctly.

However, I have noticed that in some situations the "goto declaration"-command actually does work. If, for example, I am looking at a Phoenix controller the first line in the controller module will be 

`use [namespace].Web, :controller`

here it is actually possible for me to jump to the Web module by using the "goto declaration"-command. 
Similarly, if I have an alias declaration

`alias [namespace].[module name]`

I can jump to the module using "goto declaration". However, say I have made an alias for a particular module "Foo" and then somewhere in my module I refer to a function "bar" defined in the Foo module:

`Foo.bar`

Here I _can't_ go to the bar declaration using "goto declaration". I can't even go to the Foo module using "goto declaration" from here even though it was possible when doing the alias declaration for Foo.

Furthermore, if I have two functions defined in a module and one of the functions call the other I am not able to use "goto declaration" to go to the function being called. E.g:

```
def foo() do
  bar()  #I can't use "goto declaration" here
end

def bar() do
  IO.puts "hello"
end
```

**Comment by KronicDeth** [comment]
Goto Declaration for aliases isn't implemented yet.  You can Goto Declaration for the other Modules because that is an unaliased name.

No form of Goto Declaration for functions is implemented yet.  But, for functions in the current file you can use the Structure View and Auto scroll to Source to click a function or call definition head in the Structure View to jump to that function.

**Comment by andshape** [comment]
Ah ok. Good tip about the structure view + auto scroll to source, I will use that for now.

Regarding the other part of this issue about compilation failing when making the project from within IntelliJ (Ctrl+F9) - is that to be expected even though the project can compile with "mix compile"?

**Comment by KronicDeth** [comment]
I just tried Cmd+F9 (I'm on Mac, not Windows) and https://github.com/C-S-D/alembic does not build:

![screen shot 2016-05-19 at 7 28 11 am](https://cloud.githubusercontent.com/assets/298259/15393493/46d21818-1d93-11e6-91a4-5a37ecc7d8c4.png)

But `mix compile (--force)` as a Elixir Mix run configuration works

![screen shot 2016-05-19 at 7 31 23 am](https://cloud.githubusercontent.com/assets/298259/15393581/b6d5f7ec-1d93-11e6-8b3b-cee4c7114810.png)

However, my (private) interpreter-server project does build with Cmd+F9

![screen shot 2016-05-19 at 7 33 10 am](https://cloud.githubusercontent.com/assets/298259/15393624/f8344be4-1d93-11e6-8fbc-4e465cb01218.png)

So, it is definitely possible to setup the project configuration to make it work.  I'll update when I figure out the difference between interpreter-server and alembic's setup.  I don't normally use Cmd+F9/Build Project and use `mix test` run configurations or run `mix test` from the Terminal tab, which is why I hadn't noticed the problem in alembic until now.

**Comment by KronicDeth** [comment]
Diffing .idea and the .iml for both projects I don't see an obvious difference.  Any ideas @zyuyou?

**Comment by zyuyou** [comment]
I tested `Cmd+F9` [https://github.com/C-S-D/alembic](https://github.com/C-S-D/alembic) on my mac, and I found that `Cmd+F9` did nothing to compile source file. It should be something wrong with the args passed to the compile-server.  I will check it out in my free time if I have.

**Comment by KronicDeth** [comment]
I can't reproduce this using the Alembic project anymore.  Sorry, @andshape, I'm going to have to close as can't reproduce until we find reliable reproduction case that I can debug 😞
