### ISSUE TITLE
IntelliJ 2022.3 support in 14.0.0 delisted due to before 2022.3 incorrect compatibility indicator

### ISSUE THREAD

**Issue by musialny** [KronicDeth/intellij-elixir#3074]
When support for IntelliJ 2022.3?

**Comment by Mos1ju** [comment]
when?

**Comment by KronicDeth** [comment]
https://github.com/KronicDeth/intellij-elixir/releases/tag/v14.0.0 already has support for it.  JetBrains delisted it because the compatibility in the shipped version still had it compatible with earlier versions, which it shouldn't.  You can install the update manually using the zip attached to the release by following https://github.com/KronicDeth/intellij-elixir#inside-ide-using-github-releases

**Comment by dvcrn** [comment]
2023.1 is currently also not working

<img width="462" alt="image" src="https://user-images.githubusercontent.com/688326/220561486-92d8a94a-357d-4693-82ae-f78e405fce12.png">

As an idea, can we have the CI build nightly images against the latest versions that could be downloaded manually for trying?

**Comment by kuzaxak** [comment]
Yeah, the same for me on PyCharm
<img width="439" alt="image" src="https://user-images.githubusercontent.com/5330267/229076056-8f74ae01-0745-4ec4-a2ee-977ccfc672b6.png">

**Comment by yordis** [comment]
@KronicDeth, Is there anything you think I could do to help? I am not sure what the status is with IntelliJ peeps.

**Comment by Sieabah** [comment]
This plugin is still incompatible with the latest version 2023.1

**Comment by KronicDeth** [comment]
@Sieabah JetBrains approved 15.0.1 this morning. I suggest you refresh your MarketPlace view in the IDE.

**Comment by allenwyma** [comment]
just wanted to say: to get around this I downloaded the daily alpha and installed by hand. :) You can try the same in the future @Sieabah
