### ISSUE TITLE
Auto-Inserting Matching Delimiters

### ISSUE THREAD

**Issue by nimashariatian** [KronicDeth/intellij-elixir#357]
hi guys,
first of all, AWESOME plugin.

none of the Auto-Inserting Matching Delimiters are working in my intellij IDEA for me.
example: 
if i open ( the editor just sits there and does not close the parenthesis
if i move the cursor to "do" it does not highlight "end" and so on.

is this a common issue?
i am on OSX El Capitain 10.11.15
Intellij IDEA - 2016.2

**Comment by KronicDeth** [comment]
Well, yeah, it would be a common issue as it affects all users: the feature isn't implemented yet.  I'm not actually sure which part of the OpenAPI does the insertion of matching delimiters, so it will take some research to see if the Brace Matcher API, just does the highlighting, or if it does the insertion too.

**Comment by nimashariatian** [comment]
thank you @KronicDeth 
appreciate all the hard work!

**Comment by KronicDeth** [comment]
[This](https://intellij-support.jetbrains.com/hc/en-us/community/posts/206115129-Inserting-Closing-Quote-and-Bracket) is the best posting I found in the forums so far

**Comment by jlerche** [comment]
[SimpleTokenSetQuoteHandler](https://github.com/JetBrains/intellij-community/blob/master/platform/lang-impl/src/com/intellij/codeInsight/editorActions/SimpleTokenSetQuoteHandler.java) and [PairedBraceMatcher](https://github.com/JetBrains/intellij-community/blob/master/platform/lang-api/src/com/intellij/lang/PairedBraceMatcher.java)

**Comment by KronicDeth** [comment]
@jlerche I had found those through the linked post and have an implementation of `PairedBraceMatcher`, but I don't think an instance of `SimpleTokenSetQuoteHandler` will work because the quoting for heredocs and sigil don't use the same token for the start and end token.  The start token is a promoter and the end token is a terminator of the respective sigil.  It'll probably need to borrow from stuff from SimpleTokenSetQuoteHandler and implement some of the overrides on my own.

**Comment by KronicDeth** [comment]
I wasn't able to get `)` to show up for `~r(` and I was bit stumpted, but it turned out `handleQuote` is only called if `TypedHandler` thinks the character is quote-like using [it's own rules](https://github.com/JetBrains/intellij-community/blob/e4dbca8a776eb989f02572d7ca71a02e94019970/platform/lang-impl/src/com/intellij/codeInsight/editorActions/TypedHandler.java#L199-L201)
```java
        else if ('"' == charTyped || '\'' == charTyped || '`' == charTyped/* || '/' == charTyped*/) {
          if (handleQuote(editor, charTyped, file)) return;
        }
```
So, I'll need a different type of extension to get it to recognize the sigil promoters as "quotes"
