### ISSUE TITLE
Document how to configure projects in Small (non-IntelliJ IDEA) IDEs

### ISSUE THREAD

**Issue by mrkaspa** [KronicDeth/intellij-elixir#366]
The import project doesn't work on Webstorm

**Comment by KronicDeth** [comment]
This is to be expected.  JetBrains IDEs are broken into two categories:
* Rich
* Small

Rich is IntelliJ CE and Ultimate while Small is any of language-specific IDEs, which also include Webstorm. (I'm not really sure what Webstorm's language is, I guess JavaScript?).  The import project system only works in Rich IDEs because only the Rich IDEs can have multi-language projects and projects outside their targeted language.  (It's a matter of which Extension Points you can target with the plugins.)

I don't think it's possible to *make* Elixir projects in the Small IDEs.  You can open them in them if created in IntelliJ first, but you lose some functionality.

I'd recommend using IntelliJ Community Edition, which is free (and will be able to use all the features of the plugin), if you don't have a Toolbox subscript that allows you to use both Webstorm and IntelliJ Ultimate edition.

**Comment by raarts** [comment]
This information should be at the top of the README. Configuration in for example WebStorm, PHPStorm is so much harder than in IDEA CE. The screens are all different, and it would be really handy to add something like: "although it's possible to run on the Small IDEs, the manual is written for IntelliJ CE/Ultimate, which are recommended". 

I was using WebStorm and PHPStorm, and it cost me two hours until I found this particular issue.

Anyway, many thanks for creating this. I'll try to get my current employer to make a donation.

**Comment by KronicDeth** [comment]
@raarts, so it turns out that I actually have more installs on Rubymine than even IntelliJ, and so across all Small IDEs, there are definitely more installs than IntelliJ.  I'm going to better support them in the docs from now on.

# Tasks
- [ ] Document above Import sections of README that it only applies to IntelliJ IDEA/'
- [ ] Document how to setup projects in Small IDEs (by listing all the IDEs names since users aren't going to know JetBrains' internal naming convention)
