### ISSUE TITLE
Cannot detect SDK version on osx for elixir installed with homebrew

### ISSUE THREAD

**Issue by yltsrc** [KronicDeth/intellij-elixir#390]
I have few elixir versions installed on OSX
but when I configure any of them to use, I've got an error `Cannot detect SDK version`
<img width="1176" alt="screen shot 2016-08-24 at 15 03 23" src="https://cloud.githubusercontent.com/assets/126663/17929900/3579a70a-6a0c-11e6-8949-ef7c24456897.png">
<img width="747" alt="screen shot 2016-08-24 at 15 03 34" src="https://cloud.githubusercontent.com/assets/126663/17929901/35815fe0-6a0c-11e6-983a-e43760e64b64.png">

and for each project I've got another message `Project SDK is not defined`
<img width="1431" alt="screen shot 2016-08-24 at 15 10 43" src="https://cloud.githubusercontent.com/assets/126663/17930052/f772ffb4-6a0c-11e6-864b-2c4edf5088dd.png">

and as a result I don't have access to features for elixir functions like autocomplete, go to definition, etc.

**Comment by merqlove** [comment]
It is issue when you have no default Erlang within your OS.
I'm also choose `kerl` as Erlang manager. And i have no Erlang installed in the base OS.

So i finished by putting something like that into .envrc within project directory.

.envrc
```
~/.kerlin.sh "19.0.2"
```

~/.kerlin.sh

```
#!/usr/bin/env bash

set -e

ERLANG_VERSION="19.0.2"
if [ -n "$1" ]; then export ERLANG_VERSION="$1"; fi
KERL_PATH=$(command -v kerl)
if [ ! -z $KERL_PATH ]; then
    ERLANG_INSTALLATION=$(kerl list installations | grep "^$ERLANG_VERSION " | cut -d' ' -f2)
    if [ -x "$ERLANG_INSTALLATION" ] ; then
        echo "Using Erlang $ERLANG_VERSION (in $ERLANG_INSTALLATION) via kerl."
        . $ERLANG_INSTALLATION/activate
    else
        echo "Erlang $ERLANG_VERSION not available; using default."
    fi
else
    echo "kerl not available; using default Erlang."
fi
```

```chmod +x ~/.kerlin.sh```

**Comment by yltsrc** [comment]
issue happens only in IDEA, in RubyMine it is ok
but I have erlang installed via homebrew as well

```bash
$ erl
Erlang/OTP 19 [erts-8.0.2] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Eshell V8.0.2  (abort with ^G)
```

**Comment by merqlove** [comment]
@yltsrc look at Preferences > Other settings > Elixir...
Maybe here some errors?

**Comment by yltsrc** [comment]
@merqlove yes, they are here:
<img width="1043" alt="screen shot 2016-09-05 at 13 52 51" src="https://cloud.githubusercontent.com/assets/126663/18245828/228222ae-7370-11e6-859a-3d72ec813b9e.png">

**Comment by KronicDeth** [comment]
@yltsrc which version of the plugin are you on?  I use homebrew's elixir and develop the plugin on OSX.  It's working for me with v4.3.0 (the latest release) and master.
![screen shot 2016-09-07 at 11 18 35 pm](https://cloud.githubusercontent.com/assets/298259/18336928/737c463e-7551-11e6-8a5d-67abb6917923.png)

Your error looks similar to #329, which was fixed by #343, which was released in [v4.1.0](https://github.com/KronicDeth/intellij-elixir/releases/tag/v4.1.0) on 2016-08-05.  If you are running a version before then, please update and check if you still have the issue.

**Comment by merqlove** [comment]
Same here, for me it works without errors if i use Elixir via homebrew

**Comment by yltsrc** [comment]
IDEA CE 15.0.6
Elixir plugin Version: 2.0.0-pre

**Comment by BuffaloBuffalo** [comment]
I'm having the same issue with elixir/erlang installed through homebrew. 
OSX 10.10.5
IntelliJ IDEA 2016.2.3
Elixir plugin 4.3.0 installed from github zip.

```
$ /usr/local/Cellar/elixir/1.3.2/bin/mix --version
Erlang/OTP 19 [erts-8.0.2] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
Mix 1.3.2
```
Choosing `/usr/local/Cellar/elixir/1.3.2` as the SDK Home gives the unknown elixir version error.

**Comment by KronicDeth** [comment]
@yltsrc I'm counting your original bug as solved by update.  I have no idea why you can only see 2.0.0-pre.  The [plugin website](https://plugins.jetbrains.com/plugin/7522) shows later versions and other users are able to update to the later versions.  Try uninstalling and reinstalling.

@BuffaloBuffalo, I moved your issue, because it will have a different cause to #423.
