### ISSUE TITLE
Testing workflow

### ISSUE THREAD

**Issue by merqlove** [KronicDeth/intellij-elixir#427]
Luke, hello,

I understand that this can be extended functional(as i saw any excellent testing suite within intellij or similar products always commercial), but i think all want some lite update for testing/tasks workflow:
1. Addition for `editor`:
   - `ability to run some test file`:
     -  if it has `_test` suffix & being within `test` directory.
     -  via generation of test task with file path 
   - `ability to run some test file at some line`:
     - if it has `_test` suffix & being within `test` directory.
     - via generation of test task with file path & line number
2. Addition for `file tree`: `ability to run some test file`: 
   - if it has `_test` suffix & being within `test` directory.
   - via generation of test task with file path 
   - via generation of test task with folder path

**Comment by KronicDeth** [comment]
1. I already have an issue for environment variables for Mix tasks: #216, so you should go 👍  that issue and subscribe to notifications on that one.

  You can add arguments by just editing the run configuration line.  There's nothing distinct from the mix tasks name.  (I know in Rubymine and IntelliJ those are treated distinctly, but the way @zyuyou setup the MIx task runner, it doesn't care.)  I have `mix credo --strict` (and others) setup in my work project:
![screen shot 2016-09-11 at 8 41 38 pm](https://cloud.githubusercontent.com/assets/298259/18422410/61dac646-7860-11e6-8b3e-c1b68362ed2e.png)
2. I think all those features can be reverse-engineered by looking at how IntelliJ does all that for JUnit.  The only caveats would be if the JUnit support is in the closed-source portion on IntelliJ OR if the JUnit support is privileged in some way because it's meant for Java (some of the OpenAPI APIs are only meant for use with Java code and you're left to reimplement them against just an Interface for other langauges not on the JVM).
3. Same as 2

Your list is long enough that it will count as an Epic and I (probably) won't close it with one PR.

**Comment by merqlove** [comment]
Wow, i see it now. So 1 position already done.
ENV vars is extended & maybe not needed in dev/test env.

Also 2.2 too can be difficult now...
Maybe here something useful? I'm using it all the time:
https://github.com/JetBrains/intellij-scala/tree/master/src/org/jetbrains/plugins/scala

They have:
![screenshot 2016-09-12 05 23 15](https://cloud.githubusercontent.com/assets/18354/18422954/915a8db0-78b1-11e6-9c7a-ee555d370136.png)

**Comment by merqlove** [comment]
Looks like it is here:
https://github.com/JetBrains/intellij-scala/tree/idea163.x/src/org/jetbrains/plugins/scala/testingSupport

**Comment by KronicDeth** [comment]
Resolved by #482
