### ISSUE TITLE
Switch to Gradle build system

### ISSUE THREAD

**Issue by Turbo87** [KronicDeth/intellij-elixir#445]
https://github.com/JetBrains/gradle-intellij-plugin seems to be the recommended way of building plugins for IntelliJ now. Would you be interested in switching to that build system if someone would work on a PR?

**Comment by KronicDeth** [comment]
I had originally planned to add this, but then intellij-erlang discovered [The JPS plugin (the bit that does the compiling and building of the project)](https://github.com/ignatov/intellij-erlang/issues/727) picks the project SDK instead of using JDK 1.6 and JDK 1.6 compatible classpath when building with the gradle plugin.  That bug is still open on intellij-erlang because the [feature request for gradle-intellij-plugin](https://github.com/JetBrains/gradle-intellij-plugin/issues/106) to make it safe to build JSP plugins is still open.

I worked around this issue myself using the current build system.  We can't move to the gradle plugin until it can do a safe JPS build that won't break JDK < 1.8 compatibility.

**Comment by Turbo87** [comment]
@KronicDeth I'm not sure I entirely understand the problem yet, but shouldn't it be possible to explicitly build for 1.6 by setting the `sourceCompatibility` and `targetCompatibility` properties in the Gradle projects? I did that for intellij-emberjs and it seemed to have worked fine in the past. I don't have a JPS plugin there though so I can't test for that particular issue.

**Comment by marioosh** [comment]
I made some progress with moving this project to gradle in May, But sadly I've changed the work and my time for side projects immediately shrank. ;) As far as I remember there was an issue with moving this project to gradle. I found out that change it's rather better for testing against different platforms than using it for everyday use.... but maybe my knowledge about gradle-plugin wasn't so good and one day I'd give the second try... :)
