### ISSUE TITLE
Make prereleases available via plugin repositories

### ISSUE THREAD

**Issue by NobbZ** [KronicDeth/intellij-elixir#447]
I recently found in the [intellij-golang](https://github.com/go-lang-plugin-org/go-lang-idea-plugin) plugin, that you can life on the edge without the need to manually install from a file, by following the instructions mentioned in their README via a plugin repository.

Can we have something similar for intellij-elixir pre-releases and perhaps automated nightlies?

**Comment by KronicDeth** [comment]
Branches don't get merged to master that often that there would be actual "nightlies", but I get what you're saying.

I already do have a "canary" repository that I used during the development of 4.4.0.  I announced it on twitter (https://twitter.com/KronicDeth/status/773882876244873216):

> You can add https://plugins.jetbrains.com/plugins/canary/list as a custom plugin repository (https://www.jetbrains.com/help/idea/2016.2/managing-enterprise-plugin-repositories.html) and get canary updates directly in IntelliJ now

The releases aren't automated because I'm not using the gradle plugin builder because it has a bug where it can't excluded non-JDK-1.6 compatible libraries, which breaks support for the JSP (compiler/builder) part of IntelliJ Elixir in older version of IntellIJ that don't have a shipped version of JDK 1.8.
