### ISSUE TITLE
Source / Test navigation ?

### ISSUE THREAD

**Issue by andyl** [KronicDeth/intellij-elixir#449]
Is there a way to quickly navigate between tests and their associated source file?

In RubyMine, I use `Ctrl-Shift-T` to jump between tests and source files.

Is something like this possible with intellij-elixir?

**Comment by KronicDeth** [comment]
It is a planned feature, but not implemented yet.

I mentioned adding Go To Test [here](https://github.com/KronicDeth/intellij-elixir/issues/212#issuecomment-167430441), but we can use this as the official Go To Test feature request issue.  Since I wrote that comment, it is now easier to implement Go To Test:

1) Get current module's name
2) Use `AllNames` StubIndex to find module with <name>Test
3) Open that module

To find how to extend Go To Test, I'd look for where the Navigate Test translation string is used until I find an Extension Point.

**Comment by andyl** [comment]
No java experience - sorry I can not offer hands-on coding assistance.

As a workaround - I ended up using another plugin - AltN8.  Works ok.
