### ISSUE TITLE
Auto-completion - The plugin cannot recognize some methods and modules

### ISSUE THREAD

**Issue by tieubao** [KronicDeth/intellij-elixir#473]
Hi Kronic,

Thanks for the wonderful plugin. I really love it. I'm trying to use it with my Phoenix project and I found some issues with the auto completion feature. 

It cannot pop out the completion for Ecto Repo or Mix.env or my self-written functions. I upload some pictures as below. Is it because of the plugin or my configuration?

When I import, it asked for type of project and where is Erlang SDK

<img width="288" alt="screen shot 2016-10-18 at 6 50 21 pm" src="https://cloud.githubusercontent.com/assets/1749624/19476519/dd7f855a-9563-11e6-90b8-a05ae06cb0b1.png">

<img width="774" alt="screen shot 2016-10-18 at 6 53 23 pm" src="https://cloud.githubusercontent.com/assets/1749624/19476596/338f1168-9564-11e6-9b95-f08e3c62b9b9.png">

<img width="765" alt="screen shot 2016-10-18 at 6 53 28 pm" src="https://cloud.githubusercontent.com/assets/1749624/19476599/370d307c-9564-11e6-8a7f-2f3244d128ca.png">

<img width="570" alt="screen shot 2016-10-18 at 6 37 59 pm" src="https://cloud.githubusercontent.com/assets/1749624/19476326/c1592d78-9562-11e6-8d29-ab57fcb20f3f.png">

<img width="631" alt="screen shot 2016-10-18 at 6 47 07 pm" src="https://cloud.githubusercontent.com/assets/1749624/19476422/498e420a-9563-11e6-92e4-5f932b040e2b.png">

The "red dots" indicate that IDE cannot recognize them and failed to load auto-completion.

**Comment by tieubao** [comment]
I also try to add the repo https://github.com/rubencaro/cipher but look like it still did not work

<img width="1115" alt="screen shot 2016-10-18 at 10 08 30 pm" src="https://cloud.githubusercontent.com/assets/1749624/19483759/a9167366-957f-11e6-9706-a1f90a795c3d.png">

**Comment by NobbZ** [comment]
What version of the plugin do you have installed? There is no completion of
function names before 4.5.0

Han Ngo <notifications@github.com> schrieb am Di., 18. Okt. 2016 17:10:

I also try to add the repo https://github.com/rubencaro/cipher but look
like it still did not work

[image: screen shot 2016-10-18 at 10 08 30 pm]
<https://cloud.githubusercontent.com/assets/1749624/19483759/a9167366-957f-11e6-9706-a1f90a795c3d.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/KronicDeth/intellij-elixir/issues/473#issuecomment-254538398>,
or mute the thread

**Comment by tieubao** [comment]
Wow I see, mine is 4.4.0 

<img width="802" alt="screen shot 2016-10-18 at 10 15 05 pm" src="https://cloud.githubusercontent.com/assets/1749624/19484009/5772eed0-9580-11e6-8c4c-cfe511f34e89.png">

Beside that I'm using Kiex, I'm not sure if it affects or not

<img width="808" alt="screen shot 2016-10-18 at 10 14 16 pm" src="https://cloud.githubusercontent.com/assets/1749624/19484001/4e66b3bc-9580-11e6-8422-2b219f638675.png">

**Comment by NobbZ** [comment]
Basically you 2 opt one then, either wait for 4.5 beeping released
officially or manually install the release candidate from github releases.

Han Ngo <notifications@github.com> schrieb am Di., 18. Okt. 2016 17:15:

**Comment by tieubao** [comment]
Hi @NobbZ ,

I have installed the latest version 4.5 but look like it still not work

<img width="1040" alt="screen shot 2016-10-18 at 10 55 14 pm" src="https://cloud.githubusercontent.com/assets/1749624/19485698/058a1bb0-9586-11e6-9392-b37fa65be628.png">

<img width="432" alt="screen shot 2016-10-18 at 11 07 57 pm" src="https://cloud.githubusercontent.com/assets/1749624/19486167/bda7381c-9587-11e6-80c0-fc2a99351394.png">

<img width="730" alt="screen shot 2016-10-18 at 11 08 54 pm" src="https://cloud.githubusercontent.com/assets/1749624/19486215/e0febb14-9587-11e6-806f-1a1d0c0e5512.png">

Can you guess is there something I'm doing wrong?

**Comment by KronicDeth** [comment]
You can install the canary's (including 4.5.0) by adding `https://plugins.jetbrains.com/plugins/canary/list` as a [plugin repository](https://www.jetbrains.com/help/idea/2016.2/installing-updating-and-uninstalling-repository-plugins.html).  That will allow you to get the canary or normal updates using the in-app update process.

**Comment by tieubao** [comment]
Thanks @KronicDeth. 

One more questions, is there any way to speed up the autocomplete in IntelliJ? When it comes to the functions, it's a little bit slower than the modules one.

**Comment by KronicDeth** [comment]
The way the `PsiReference#getVariants` API works, you're not supposed to do prefix filtering, so if you do an unqualified function call, it's constructing `LookupElement` for every function currently in the index and then the parts of OpenAPI that calls getVariants does the actual filtering based on prefix.  (It doesn't just return those functions that are in scope unqualified now in order to allow a Quick-Fix (to be implemented later) to add `import`s, similar to how static importable methods work for Java in IntelliJ.)  I could pre-filter the return from `getVariants` to not show all the functions and it would make it faster by saving a lot of allocations.  I'm not sure if that violates some post-condition on the API though.

Qualified function completion is faster because it's not using `PsiReference#getVariants()`, it's using a custom `CompletionContributor` that only shows the public/private functions and macros in the qualifying macro.

I could not use the `PsiReference#getVariants()` and make a custom `CompletionContributor` for unqualified functions.  That would guarantee I'm not violating some post-condition of `#getVariants()`.  I should probably open an question on the OpenAPI forums to see if there's a caching layer I should be using too.

**Comment by tieubao** [comment]
Thanks for the answer @KronicDeth . Keep up the great work!
