### ISSUE TITLE
If I try to use other intellij themes looks bad

### ISSUE THREAD

**Issue by mrkaspa** [KronicDeth/intellij-elixir#505]
I'm trying to use this http://color-themes.com/?view=theme&id=563a1a6a80b4acf11273ae64

![screen shot 2016-11-12 at 10 06 25 pm](https://cloud.githubusercontent.com/assets/764271/20243417/5ec439de-a924-11e6-9ab2-98f21b57f343.png)

**Comment by KronicDeth** [comment]
Other themes aren't my problem unless you can point out a specific a `AttributeKey` that I'm using inappropriately for how it's used in the included themes in "Default" and "Darcula".  I have no control over the colors that theme is picking and it's that theme's maintainer that must adapt to the `AttributeKey`s that are unique to IntelliJ Elixir except in those case where the `AttributeKey` is a generic one that is authorized by JetBrains as an ancestor/fallback for all language-specific color schemes.  In IntelliJ 15 (IIRC) JetBrains switched up which `AttributeKey`s could be used as fallbacks.  It maybe that theme looks good for JetBrains developed plugins because they're still using the Java-derived `AttributeKey`s that aren't supposed to be used anymore OR the theme has specific support for the JetBrains supported plugin `AttributeKey`s.  A random theme shouldn't be expected to work with a new language plugin because each language must under the 15+ rules define their own AttributeKeys.

**Comment by rawkode** [comment]
So what color schemes do support Elixir? Because everything on my end looks terrible :disappointed:

**Comment by rawkode** [comment]
@KronicDeth Are you saying we should take those colorscheme's we like and add additional attributes for Elixir?

**Comment by KronicDeth** [comment]
@rawkode I use Darcula, so I made sure that looked good.  When doing that to get a distribution across the color circle I did some math using HSB color, I then applied that math to the Default color scheme with one or two manual tweaks.   This process is outlined in https://github.com/KronicDeth/intellij-elixir/blob/master/COLOR_SCHEME_DESIGN.md, but in general since IntelliJ 15 (when JetBrains changed the constant class and told plugins to stop using the Java color constants), any non-Java language will end up using the fallback colors that are language neutral.  Many element types in the Elixir palette use the same fallback because the language-neutral fallbacks are so generic.  Because I was able to set overrides for known theme names both Darcula and Default have those overrides.

You can either open a PR to tweek the Darcule and Default overrides OR add new overrides for some theme name that you normally use.  I welcome PRs that redo the color for better contrast or readability.  I'm not a color designer, I just picked distribution on the HSB color wheel using simple edition and rotations.

New theme overrides go in `res/colorSchemes` and then they are declared in the `plugin.xml`:

```
    <additionalTextAttributes file="colorSchemes/ElixirDarcula.xml" scheme="Darcula"/>
    <additionalTextAttributes file="colorSchemes/ElixirDefault.xml" scheme="Default"/>
```

**Comment by vassilevsky** [comment]
Interesting idea: https://plugins.jetbrains.com/plugin/8214-rainbow
Supports Elixir.

**Comment by scullionw** [comment]
even on darcula it looks different that darcula with any other language. can you confirm this is what darcula looks like to you?

<img width="2344" alt="Screenshot 2024-01-23 at 7 15 17 AM" src="https://github.com/KronicDeth/intellij-elixir/assets/11668344/e8469af9-fa6b-42ba-bbb9-4a9e6121a2df">

**Comment by guillermo-st** [comment]
> even on darcula it looks different that darcula with any other language. can you confirm this is what darcula looks like to you?
> 
> <img alt="Screenshot 2024-01-23 at 7 15 17 AM" width="2000" src="https://private-user-images.githubusercontent.com/11668344/298936790-e8469af9-fa6b-42ba-bbb9-4a9e6121a2df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4MTA2OTEsIm5iZiI6MTcwODgxMDM5MSwicGF0aCI6Ii8xMTY2ODM0NC8yOTg5MzY3OTAtZTg0NjlhZjktZmE2Yi00MmJhLWJiYjktNGE5ZTYxMjFhMmRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDIxMzMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0YjA0NjczYTY4MTYzN2YzYWMxMDA1ODM3ZjgzMmNkZTU3MWZhYTY0YjI0Y2FjMTk1N2IxMzkxM2FmYTUyMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-nzslOPAYZyKrnKCjTfk98hAM34j-om_ITVxqduKZFM">

Yeah, the bright colors are super jarring for me too. I ended up manually editing the colors one by one
