### ISSUE TITLE
Space needed between variable name and match in autocomplete

### ISSUE THREAD

**Issue by joshuataylor** [KronicDeth/intellij-elixir#506]
Looks like local variables don't have the correct spacing, everything else is fine.

Linux/IntelliJ

Screenshot:

![b63ptiu](https://cloud.githubusercontent.com/assets/298259/20253849/a749750e-a9f4-11e6-9e3a-450ce292db66.png)

**Comment by KronicDeth** [comment]
What do you mean incorrect spacing?  What specifically in the screen shot is spaced incorrectly?

**Comment by joshuataylor** [comment]
Sorry, if you look at foo, there doesn't seem to be a space between `foofoo = 1`?

The force_compile seems to have a double space.

It just looks super cluttered - not sure if this can be fixed on my end in the editor (I'm sure this is a setting somewhere now I think about it :))

**Comment by KronicDeth** [comment]
O yeah, sorry, I wasn't seeing the second `o` in the first `foo`.

I think there's no space because they completion is setup for bare variable names OR a prefix match as for the function.  (Think about how it works for Java.)  I can't do a prefix match like with functions because the variable may be declared as the right operand of the `=` in a pattern, but I can't recall why I didn't just add a space, so I'll do that.
