### ISSUE TITLE
Font colour issues

### ISSUE THREAD

**Issue by joshuataylor** [KronicDeth/intellij-elixir#508]
I'm getting weird font colour issues, such as the following:

![frvnc3i](https://cloud.githubusercontent.com/assets/298259/20650738/4740449c-b49b-11e6-8550-f9cc68eb85d9.png)

IntelliJ/Linux

**Comment by KronicDeth** [comment]
I've seen similar things myself before.  I assume it's some race between the different annotators.  I may have to either unify the annotators into a single decision tree OR add rules so that the annotations that should be lower priority aren't applied when a higher-priority one will win.  I'm not aware of an OpenAPI system to do that, so maybe they expect implementors to use a single decision tree.

**Comment by joshuataylor** [comment]
@KronicDeth If it helps, I haven't seen this before the last release.

**Comment by mbriggs** [comment]
fwiw, im seeing this with my error log clean on the latest build

![image](https://cloud.githubusercontent.com/assets/89260/20727452/86e60f02-b647-11e6-9e02-3c27928454da.png)

**Comment by KronicDeth** [comment]
This should have been fixed by #627, which was merged as 610853ab3ed8baae65c7ef44ecc6b01eb17f6d16, which was part of [v5.0.0](https://github.com/KronicDeth/intellij-elixir/releases/tag/v5.0.0).  If running with v5.0.0 or v5.1.0 still show the issue for you, I'll reopen.
