### ISSUE TITLE
Completion for Aliases to .beam-only Modules

### ISSUE THREAD

**Issue by mbriggs** [KronicDeth/intellij-elixir#541]
using 4.6.0

Let me know if you want any more info, not sure what would be helpful

![image](https://cloud.githubusercontent.com/assets/89260/20725794/054993f2-b641-11e6-9cf8-c7869d4915cf.png)

would expect to see this - http://elixir-lang.org/docs/stable/elixir/Application.html

**Comment by KronicDeth** [comment]
If you mean the `Application` from the standard library, then yeah, that makes sense, completion only works for parsable-code and your standard-library is only available in precompiled `.beam`-files.

**Comment by KronicDeth** [comment]
This may actually be fairly simple because the rules for Elixir modules: just scan the paths for `Elixir.*.beam` files and `*` is the name of the aliases that can be completed.  This may be a feature that can be added quicker than completion for functions in `.beam`-only modules.

**Comment by gliwka** [comment]
Would it be possible to utilize elixirs  autcompletion capabilities, since it's already installed on the system? 

A project doing this that way is https://github.com/wende/autocomplete-elixir - take a look at https://github.com/wende/autocomplete-elixir/blob/master/lib/alchemide/autocompleter/autocomplete.exs.

**Comment by gliwka** [comment]
Would it be possible to utilize elixirs autcompletion capabilities, since it's already installed on the system? 

A project doing this that way is https://github.com/wende/autocomplete-elixir - take a look at https://github.com/wende/autocomplete-elixir/blob/master/lib/alchemide/autocompleter/autocomplete.exs - they're using the autocomplete function of the IEx module.

**Comment by gliwka** [comment]
Would it be possible to utilize elixirs autcompletion capabilities, since it's already installed on the system? 

A project doing this that way is https://github.com/wende/autocomplete-elixir - take a look at https://github.com/wende/autocomplete-elixir/blob/master/lib/alchemide/autocompleter/autocomplete.exs - they're using the autocomplete function of the IEx module.

**Comment by KronicDeth** [comment]
Works after #574 

![screen shot 2017-01-01 at 7 44 54 pm](https://cloud.githubusercontent.com/assets/298259/21583935/e3c31454-d05a-11e6-990a-080222f37436.png)

**Comment by mbriggs** [comment]
great work man, excited for 4.8 :D I think when this lands, we'll have the nicest completion out of all the various implementations, which is quite an accomplishment!
