### ISSUE TITLE
`fn name () do body end` breaks syntax highlighting

### ISSUE THREAD

**Issue by Havvy** [KronicDeth/intellij-elixir#547]
Minimal example. Put some other function def below it to show the syntax highlighting broken.

`_ = fn () do nil end`

**Comment by KronicDeth** [comment]
Why are you expecting it to work?  `_ = fn () do nil end` is invalid Elixir code in the native parser:

```
Code.string_to_quoted("fn () do nil end")
{:error, {1, "missing terminator: end (for \"fn\" starting at line 1)", ""}}
```

The only reason there is no warning in the edtiro for that line alone is probably because of the various error recovery mechanisms built into the parser generator.  It's probably something to do with `do` `end` being marked as a structural block, so it will match those even though there should be an error OR I made the grammar more forgiving there for some other reason.

So, once an error happens at the lexer or grammar parser level, all other levels of highlighting don't run (this is just how the libraries that JetBrains supply work), so you don't get highlighting because there is a grammar-level error in the sample code.

Do you want to (1) convert this to a request to enhance the errors shown for that line OR (2) close because the code is invalid, so it should affect sibling highlighting?

**Comment by Havvy** [comment]
Probably #1, although that would be more on the Elixir side than on the IDE side.
