### ISSUE TITLE
Atom and String colors are too close in Default theme

### ISSUE THREAD

**Issue by kostonstyle** [KronicDeth/intellij-elixir#569]
Hi all 

It would be nice, if the value of a struct would have an other color then the key itself.
<img width="911" alt="screen shot 2016-12-20 at 20 55 27" src="https://cloud.githubusercontent.com/assets/701611/21365720/d7d63828-c6f6-11e6-94fc-e09114415869.png">

For example http://www.foo.com/ should have an other color then bUri.

Thanks

**Comment by KronicDeth** [comment]
Can I convince you to switch to the Darcula (dark) theme instead of the Default (light) theme?  I personally use Darcula, so I spent more time ensuring good contrast and visual pop.  Darcula doesn't have your issue:

![screen shot 2016-12-20 at 6 12 58 pm](https://cloud.githubusercontent.com/assets/298259/21372931/2438538e-c6e0-11e6-8710-e015547ba83c.png)

If you prefer Default (light) theme, I can look into why the contrast math ended up with a collision and just tweak it by hand so that atoms don't have the same color as strings.

**Comment by kostonstyle** [comment]
Yes, I am using default.
THanks

**Comment by KronicDeth** [comment]
@kostonstyle, you didn't need to close the issue.  I would count it as a bug that for the Default theme the atom color is too close to the String color.
