### ISSUE TITLE
syntax highlighting: parameter variable style incorrectly applied

### ISSUE THREAD

**Issue by mbriggs** [KronicDeth/intellij-elixir#577]
given

```elixir
defmodule Foo do
  def get_products(store, opts \\ %{}) do
    get(store, query("products.json", opts))
  end

  defp query(path, params) when params == [], do: path
  defp query(path, params) when params == %{}, do: path
  defp query(path, params), do: "#{path}?#{URI.encode_query(params)}"
end
```

I get

![image](https://cloud.githubusercontent.com/assets/89260/21593688/be48ed2e-d0e7-11e6-8507-4d01529d1037.png)

There are two issues at play there.

1) the two `defp query` as well as the callsite for `query` are highlighted with my "Variables -> Parameter" style. (italicized brown)
2) the last `defp query` has the `query` portion in my `Variables -> Variable` style (light blue)

if I remove the call to `query`, things seem to become good (there is another issue visible there, but i will log it in another ticket)

![image](https://cloud.githubusercontent.com/assets/89260/21593725/370cc8b6-d0e8-11e6-84b9-8db213f0d70c.png)

**Comment by KronicDeth** [comment]
Very nice bug report

**Comment by KronicDeth** [comment]
This appears to be fixed by other changes on `master` as of https://github.com/KronicDeth/intellij-elixir/commit/57c9b397a749880284208af901034f035fa31c66.

## v4.7.0

<img width="513" alt="screen shot 2017-03-11 at 10 37 39 am" src="https://cloud.githubusercontent.com/assets/298259/23825864/ed060df6-0646-11e7-950d-cf0f45254d26.png">

## https://github.com/KronicDeth/intellij-elixir/commit/57c9b397a749880284208af901034f035fa31c66

<img width="497" alt="screen shot 2017-03-11 at 10 33 54 am" src="https://cloud.githubusercontent.com/assets/298259/23825867/f77d87f0-0646-11e7-983c-c5c8274b968e.png">
