### ISSUE TITLE
Hang when creating project from mix project sources when hex asks whether to update

### ISSUE THREAD

**Issue by BryanJBryce** [KronicDeth/intellij-elixir#604]
When creating a new project from an existing mix project the IDE hangs on Fetching dependencies. 

# Actual

Below the loading bar it reads

```
Shall I abort the current command and update Hex? [Yn].
```

I'm guessing that `hex` is waiting for a `Y` or `n` here and for that reason there is no progress. 

Clicking cancel doesn't cancel. In macOS I have to force quit to get out.

# Expected

Skip hex update

**Comment by KronicDeth** [comment]
> ```elixir
>      not Version.match?(Hex.version, @hex_requirement) ->
>        Mix.shell.info "Mix requires Hex #{@hex_requirement} but you have #{Hex.version}"
>
>        if Mix.shell.yes?("Shall I abort the current command and update Hex?") do
>          Mix.Tasks.Local.Hex.run ["--force"]
>          exit({:shutdown, 0})
>        end
> ```
> -- https://github.com/elixir-lang/elixir/blob/v1.5/lib/mix/lib/mix/hex.ex#L34-L40

**Comment by KronicDeth** [comment]
Looking at the code, the Expected can't be skipping the hex update because the hex update is being forced because the hex requirement for the version of mix you're using is newer than the installed hex, so if the hex update is skipped, so would the entire dependency fetch.

I think I need to either
1. Always update hex.
2. Detect the prompt and ask what to do.
3. Detect the prompt and always bail and don't update the dependencies.

(1) is the simplest as I don't need to read the stdout and interact with stdin from `mix`.  I'll see how hard it is to do (2) or (3)

**Comment by KronicDeth** [comment]
I can reproduce with `mv ~/.mix ~/.mix.bak` and opening any project from existing sources with Fetch Dependencies checked.
