### ISSUE TITLE
Slow Kernel annotator

### ISSUE THREAD

**Issue by merqlove** [KronicDeth/intellij-elixir#622]
Now we have large timeout to render language default words.

I can illustrate it through example.
First part is Elixir, second Java/Scala IDE.
https://www.dropbox.com/s/a5ruv6t8d5xy05l/intellij-elixir-slow-render.mp4?dl=0

**Comment by KronicDeth** [comment]
Scala is probably lexing things like `implicit` and `trait`.  The first pass of the highlighter is quick because it's keyed off the lexed `ASTNode`s, but in Elixir, `defmodule` isn't a keyword, it's just a macro, so it doesn't show up as a distinct `ASTNode` that can be highlighted in the first pass highlighter, instead it is highlighted by the [Kernel](https://github.com/KronicDeth/intellij-elixir/blob/v4.7.0/src/org/elixir_lang/annonator/Kernel.java) annotator.  These annotators don't run as fast and I don't think are applied right-away the way the ASTNode highlighting is.

So, you should expect different behaviour than the Scale plugin because they aren't keywords in Elixir, but I can maybe look if there's a way to speed up the annotator.

If you look at the video `do` is highlighted right-away, because it's a lexed ASTNode and really is a keyword in Elixir's syntax.

**Comment by merqlove** [comment]
Yeah, i c, just as a suggestion, maybe here some hacks over Intellij to get it faster :)

**Comment by KronicDeth** [comment]
The `Kernel` annotator was merged with the `Calleable` annotator in #736.  This merging made the time-to-highlight for `Kernel` functions slower because it's determining that the resolved function is in the decompiled or SDK source Kernel module now, so it's far more accurate than the old `Kernel` module, but will be slower.  Since it's a different approach now, I think we'll open it as a separate bug, since it will be have to be tuned differently.

**Comment by KronicDeth** [comment]
#766 caches references, so that would lead to speed-ups for the annotator, which uses references
