### ISSUE TITLE
Allow jumping to either source or .beam file

### ISSUE THREAD

**Issue by fxn** [KronicDeth/intellij-elixir#667]
I am browsing the source code of Elixir itself, and go to definition for `Protocol.__protocol__` (to put just one example) jumps to partially decompiled code from _Elixir.Protocol.beam_, instead of going to the available definition in _protocol.ex_. (Using 5.0.0.)

Thanks for the plugin 😄 .

**Comment by zoltanmaric** [comment]
It would be nice if jumping to decompiled files could be disabled completely, including jumping to alias declarations. I don't see it particularly useful to jump to the alias declaration, and other languages don't have it either. E.g. if you go to definition in Java or Scala, there's no option to jump to the `import` statement, which would be the equivalent of an alias in Elixir.

**Comment by eagle-te** [comment]
I would like that too.
I'm finding myself often searching for the name of function, instead of using intellij's GOTO declaration, because I end up in the .beam files. There are some exception where it presents me with some options for either, but that is rare.

I already tried running mix compile with re-indexing, resulting in no resolve.

tyvm for the plugin!

**Comment by KronicDeth** [comment]
@eagle-te you can use the Structure View for in-file jump to file too as a work-around.

**Comment by eagle-te** [comment]
@KronicDeth 
Well, there is no problem if the targeted function is declared inside the same module(file) I'm currently in.
The Problem occurs if the targeted function is declared in another module(file).

Sorry for being unclear.

**Comment by KronicDeth** [comment]
I don't see a way to add a new checkbox beyond the "Include non-project files" as I control the `GotoSymbolContributor`, not the UI for Goto Symbol itself.  I'm going to filter out decompiled navigation items if and only if a source navigation item of the same kind and values exists.

I'm not sure how to restore Go To Symbol for decompiled modules and functions when there is source.  I may have to use Show Bytecode or GoTo Decompiled Class which both Java and Kotlin use, but with slightly different meaning.

**Comment by KronicDeth** [comment]
So, interesting bug - because the Go To Declaration is based on static analysis, I determine it is done by checking when it resolving the reference loops back on itself, which was fine, until decompiling was introduced because with the decompiled module, the source module references itself *AND* the decompiled module while the decompiled module only references itself, so the decompiled module is the root of tree.

Fixing it the same way as `GoToSymbolContributor` - if there is both source and decompiled, use only the source version, which is a really small diff actually:

```
Index: src/org/elixir_lang/reference/resolver/Module.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/org/elixir_lang/reference/resolver/Module.kt	(date 1536027190000)
+++ src/org/elixir_lang/reference/resolver/Module.kt	(date 1536031292000)
@@ -1,9 +1,11 @@
 package org.elixir_lang.reference.resolver
 
 import com.intellij.openapi.project.Project
+import com.intellij.psi.PsiElement
 import com.intellij.psi.PsiElementResolveResult
 import com.intellij.psi.impl.source.resolve.ResolveCache
 import org.elixir_lang.Reference.forEachNavigationElement
+import org.elixir_lang.beam.psi.BeamFileImpl
 import org.elixir_lang.psi.scope.module.MultiResolve
 import org.elixir_lang.reference.module.ResolvableName.resolvableName
 
@@ -41,6 +43,14 @@
             true
         }
 
-        return resolveResultList.toTypedArray()
+        val sourceResolveResultList = resolveResultList.filter { !it.element.isDecompiled() }
+
+        return if (sourceResolveResultList.isNotEmpty()) {
+            sourceResolveResultList.toTypedArray()
+        } else {
+            resolveResultList.toTypedArray()
+        }
     }
 }
+
+private fun PsiElement.isDecompiled(): Boolean = containingFile.originalFile is BeamFileImpl
```

**Comment by zoltanmaric** [comment]
Thanks a lot @KronicDeth! I find the user experience so much better now! Keep 'em coming! :)
