### ISSUE TITLE
Using intellij-elixir with Vagrant

### ISSUE THREAD

**Issue by asheehan** [KronicDeth/intellij-elixir#675]
Is it possible to use a Vagrant remote elixir sdk with this plugin?  I'm trying to setup a run configuration so that I can do a basic `mix test` that run on my local vagrant environment (ubuntu/xenial64).  I don't see an easy way to do this via Intellij.  Any thoughts?

This plugin is amazing.  Many thanks.

**Comment by KronicDeth** [comment]
You just need to be able to select the Elixir SDK path and mix paths from outside of vagrant.  I have no idea what IntelliJ's normal support for vagrant is.  Here's the [help for 2017.1 for Vagrant](https://www.jetbrains.com/help/idea/2017.1/vagrant.html), so follow that and if something works for Java development under Vagrant, but doesn't work for Elixir development, let me know and I'll try to fix it; otherwise, there's not much I can do because the base IDE doesn't really support it.
