### ISSUE TITLE
erl_anno.erl:318: :erl_anno.set(:location, -1, [location: -1, generated: true])

### ISSUE THREAD

**Issue by andshape** [KronicDeth/intellij-elixir#680]
I have tried using the new graphical debugger (great feature to have by the way) and I am getting the following error:

[error] Process #PID<0.243.0> raised an exception
** (ArgumentError) argument error
    (stdlib) erl_anno.erl:318: :erl_anno.set(:location, -1, [location: -1, generated: true])

This problem has been mentioned here:
https://github.com/KronicDeth/intellij-elixir/pull/643

From what I can gather from https://github.com/KronicDeth/intellij-elixir/pull/643 this might be caused by an outdated dependency. Is that correct?

Is there any work around to this (except updating the outdated dependency if that is indeed the problem)?

**Comment by KronicDeth** [comment]
You may need to update your dependencies OR you may even need to run with Elixir 1.5.0-dev built from the git repo.  Personally, I can use the debugger in alembic and calcinator fine with Elixir 1.4.2, but I need to use 1.5.0-dev for retort or our primary work repo because of the bug fixes for https://github.com/elixir-lang/elixir/issues/6015.

**Comment by andshape** [comment]
Alright, I will try that. Thanks for the info.
