### ISSUE TITLE
Impossible to create run configuration

### ISSUE THREAD

**Issue by openscript** [KronicDeth/intellij-elixir#711]
I'm trying to create a run configuration. I've read the documentation and failed.

![image](https://user-images.githubusercontent.com/1105080/26936601-6bedac64-4c6f-11e7-9087-71b377485d1e.png)

![image](https://user-images.githubusercontent.com/1105080/26936633-85eb7010-4c6f-11e7-8ff1-d583c062441f.png)

I just need to run 'mix phoenix.server' in the project root. How can I achieve this?

**Comment by KronicDeth** [comment]
The `""` between `elixir` and the program arguments is the path to mix.  That indicates your mix path is not set.  This normally happens when users open the project as a directory instead of importing it as a mix project.  To import as a mix project use [Import project from external model](https://github.com/KronicDeth/intellij-elixir#import-project-from-external-model).

Once you'd fixed your mix path, you won't put `mix` itself in the program arguments, just the arguments to mix, so you'd put `phoenix.server` in "Project arguments", not `mix phoenix.server`.

**Comment by openscript** [comment]
Thank you @KronicDeth! It's up and running :-)
