### ISSUE TITLE
Support for Elixir documentation

### ISSUE THREAD

**Issue by rhumbertgz** [KronicDeth/intellij-elixir#740]
Hello,

Could be possible to enable  Elixir documentation through "Quick Documentation"? 

I was trying to do it in the same way that I added the Elixir source code:
![screen shot 2017-07-20 at 16 06 49](https://user-images.githubusercontent.com/10393245/28421563-d8bf8f30-6d65-11e7-998f-85c77e9e21e1.png)
Doing this I got the autocomplete for the core-libs of Elixir, but the documentation doesn't work for me. I tried with several sources as you can see:
![screen shot 2017-07-20 at 16 07 37](https://user-images.githubusercontent.com/10393245/28421686-2f233fa2-6d66-11e7-9db7-9535e26e3809.png)

Any suggestion? Is there a way to do it?

Thanks in adavance,
Humberto

**Comment by KronicDeth** [comment]
I don't think using Documentation Paths would be a good idea since that's rendered HTML, but I'd have to look at how the Documentation Paths work for Java to figure out if they can consume HTML.  

I would probably implement this in two features:

1. If the source is available, then get the @doc and @moduledoc and show that.
2. If the source is not available, then decompile the `.beam` and get the @doc and @moduledoc output of that and put it in the decompiled version of the `.beam`.  This fake source will then be parsed by (1) and it will work as normal.

But yeah, if linking to hexdocs.pm worked, that would be crazy awesome too.

**Comment by rhumbertgz** [comment]
@KronicDeth thanks for your fast reply!

**Comment by OvermindDL1** [comment]
> But yeah, if linking to hexdocs.pm worked, that would be crazy awesome too.

This would be killer!

**Comment by smeevil** [comment]
+1

**Comment by CptnKirk** [comment]
+1

**Comment by Aetherus** [comment]
+1

**Comment by Znack** [comment]
+1 it should be amazingly useful

**Comment by simoneggler** [comment]
+1

**Comment by Nimamoh** [comment]
+1

**Comment by Tsuyoshi84** [comment]
+1

**Comment by eagle-te** [comment]
+1

**Comment by dwhelan** [comment]
+1

**Comment by IvanShpotenko** [comment]
+1

**Comment by CleytonGoncalves** [comment]
+1. Btw thanks for your amazing work!

**Comment by blakedietz** [comment]
+1. Thank you for your hard work Kronic.

**Comment by swalloda** [comment]
+1

**Comment by Timtonix** [comment]
+2

**Comment by KronicDeth** [comment]
This was added in #1792 and first released in [v11.8.0](https://github.com/KronicDeth/intellij-elixir/releases/tag/v11.8.0) on August 4th 2020.

**Comment by KronicDeth** [comment]
@swalloda @Timtonix it was already there when you +1’d the feature.
