### ISSUE TITLE
Kernel.SpecialForms `alias` has wrong color

### ISSUE THREAD

**Issue by JanStevens** [KronicDeth/intellij-elixir#780]
Keyword alias has the wrong color, its white where I expect it to be red (the same as `defmodule`, `use` and `import`)

![screen shot 2017-08-07 at 13 17 12](https://user-images.githubusercontent.com/1540483/29024524-bbcae0ee-7b72-11e7-8cab-a2385c82a3c8.png)

Also `import` is red outside quote blocks but inside quote blocks not

**Comment by KronicDeth** [comment]
I think `alias` is different than `import` because as a special form, `alias` is [only declared as 2-arity](https://github.com/elixir-lang/elixir/blob/v1.5.1/lib/elixir/lib/kernel/special_forms.ex#L509) even though it can of course be called a 1-arity.  I think what's happened is that when the Kernel annotator was separate from the Callable annotator, I had special cases the special forms to compensate for the undeclared arities, but that's lost now.
