### ISSUE TITLE
Add possibility to remove ugly horizontal line above module attributes

### ISSUE THREAD

**Issue by mkaput** [KronicDeth/intellij-elixir#798]
Is there an option to remove/hide this line above `@doc`? I cannot find anything related nor even I don't know how it's called.

![zrzut ekranu z 2017-08-18 10-39-31](https://user-images.githubusercontent.com/3450050/29451085-9eb82182-8401-11e7-970e-cdb049be4527.png)

**Comment by KronicDeth** [comment]
The line is not above all module attributes: it is above the group of `@doc`, `@spec`, and call definition clauses that are associated.

You can turn them off in Preferences > Editor > General > Appearance.

![screen shot 2017-08-18 at 12 07 28 pm](https://user-images.githubusercontent.com/298259/29469447-f44ee93a-840d-11e7-8364-32c7cfe25fa8.png)

They're called Method Separators.

If you're wondering why they're called "method" and not "definition" separators, it's because it's a cross-language settings, so the name is the one IntelliJ uses for Java.  I don't control that part of the menu structure.

**Comment by mkaput** [comment]
Sorry for late response, but I don't have Elixir set up on my personal machine and had to try it at work.

I already have this option turned off (and I think it's off by default):
![obraz](https://user-images.githubusercontent.com/3450050/29506364-95cfb656-864b-11e7-9324-3db00ae1ebbe.png)

**Comment by seanwash** [comment]
Sort of the opposite, but I really like the method separators. Is there any way to configure things so that they appear above the `describe` and `test` macros as well? I'd be happy to provide a PR if I could get some guidance.
