### ISSUE TITLE
Disable formatting?

### ISSUE THREAD

**Issue by joshuataylor** [KronicDeth/intellij-elixir#807]
I'm currently experiencing high CPU and freezing, and very low delays on certain files, and I have a feeling it's the formatter. Can I disable it to test?

**Comment by KronicDeth** [comment]
There's no way that I know of to disable the formatting that happens in the background when you type new stuff and that happens when it reads the file to cache the formatting of the parent node when you type new stuff.  There is a [format disable mark system](https://www.jetbrains.com/help/idea/reformatting-source-code.html), but I didn't write anything specific to support it and I'm not sure if it works automatically by inferring the comment format for Elixir (which the parser exposes) and then token you set in that menu.

Otherwise, you can rebuild the plugin locally using the [Contributing Guide](https://github.com/KronicDeth/intellij-elixir/blob/master/CONTRIBUTING.md).  If you comment out these lines before using the `runIde` gradle tasks, it should disable all the code for the formatter.

https://github.com/KronicDeth/intellij-elixir/blob/70ecf4e538a30f7f851c8888cd43428be544b46a/resources/META-INF/plugin.xml#L88-L91

**Comment by KronicDeth** [comment]
@joshuataylor since you're still an active user of the plugin I assume this isn't an issue for you anymore, so I'm closing.  Let me know if it is.

**Comment by joshuataylor** [comment]
Yes, everything has been working pretty much perfectly. :-)
