### ISSUE TITLE
Formatting options

### ISSUE THREAD

**Issue by smeevil** [KronicDeth/intellij-elixir#809]
Hi,

I was wondering if it would be possible to add a few options to the formatting.

- Don't break function heads into multiple lines.

(update, these are solved by updating the character line limit)
- ~~Don't break @spec definitions into multiple lines.~~
- ~~Don't break lines so they fit the 80 character line limit.~~

These are the only things that I ran into, otherwise I'm really happy with the results!
Thanks you so much, once again, for your continuous time and effort :)

Gerard.

**Comment by KronicDeth** [comment]
`Don't break lines so they fit the 80 character line limit.` <- That's pretty much the entire `Wrap` system.

If you want it to be longer, you can raise the Right Margin in Preference > Editor > Code Style  and it will wrap at that column count instead, for example, I normally use 120 columns instead of 80.  If you want the column rule to show up at 80, but the wrapping to occur at a different column count, then I can add a separate Right Margin for Elixir, which is how Java's settings work: it uses the General setting that matches the Preferences > Editor > General > Appearance > Show Right Margin, but you can set a Java specific one to separate the visual column indicator from the formatters wrap cut-off.  If you want it completely off, that will be more complicated.  I guess I'd have to check the setting in each location and always use `WrapType.NONE`.

**Comment by smeevil** [comment]
Ah nice that it piggybacks on those setting, completely did not think about that! This is perfectly acceptable. Thanks :)

**Comment by smeevil** [comment]
Reopening this one, Just realised that the line wrapping solved part if the problem.
Function heads are still broken in multi lines when pattern matching a map for example.

```defp validate_level(%{changes: %{expertise_id: expertise_id}} = changeset) do```
will become

```
defp validate_level(
         %{
           changes: %{
             expertise_id: expertise_id
           }
         } = changeset
       ) do
```

**Comment by KronicDeth** [comment]
The multi-lining is the keyword exclusivity rule: only one level of keywords are allowed per line.  There's two ways to treat it differently:
1. Completely turn it off
2. Only wrap if there is a keyword at the level 1 after there being one at level 2, so that you can descended levels, but you can't zigzag up and down levels in one pattern (since that requires you to keep track of the `{` and `}` matching stack in your head.

Do you prefer one over the other?

**Comment by smeevil** [comment]
I'd prefer to turn it off for function heads and only apply the whitespace rules for it.

**Comment by KronicDeth** [comment]
I don't think I currently have anything specific to function heads, so I'll have to figure out how costly it is to detect function heads to turn it off in function heads only.

**Comment by smeevil** [comment]
Stale now because of mix format
