### ISSUE TITLE
Editor became slow when there are more than 300 lines in file

### ISSUE THREAD

**Issue by CalixHu** [KronicDeth/intellij-elixir#822]
I have some .exs files(unit test) that contain more than 300 lines(some 1000+). When I hit the 'enter', or do a copy/paste, the editor is frozen for 1-2 seconds. I have turn off all the plugins except the intellj-elixir. However, when I turn off this one, everything works fine. I have increased my memory for the idea VM. Is there a solution for this? I just turned from emacs and this plugin help me a lot.
Thanks.

**Comment by KronicDeth** [comment]
Do you have a lot of stabs in the file?  That is `->`s?  There's a known performance issue with the grammar because it needs to do look-aheads and backtracks to determine if the next line is the starting `expression ->` or just an expression in the body of the last clause.

**Comment by CalixHu** [comment]
Yes, I do have lots of that. We have some mock functions in unit test to reduce the duplicates work. Is it possible to fix the issue? Or some workaround?
Thanks.

**Comment by KronicDeth** [comment]
Yeah, it's possible to fix the issue? Sure.  Do I understand how to fix it? Not really. See https://github.com/KronicDeth/intellij-elixir/issues/580.

Work-arounds in your own Elixir code are to have fewer `->`, so have more named functions that you take references to with `&` instead of inlined `fn` with `->`.

If you can post the the file that causes the problems, I can use it as a test case for #580.  Go 👍  the description for #580 to vote for it too.

**Comment by CalixHu** [comment]
OK, thanks for replying so quickly and give us an awesome tool. : )
