### ISSUE TITLE
Plugin not detecting syntax

### ISSUE THREAD

**Issue by michaelbuckner** [KronicDeth/intellij-elixir#83]
Hello,

I've tried the plugin on both RubyMine and IntelliJ on a  PC and a Mac. I'm not getting any auto-complete or syntax highlighting on either.

Is there some additional configuration required?

**Comment by KronicDeth** [comment]
Have you read through #6 and confirmed you're not having the same issue: the syntax highlighter is incomplete and you're not noticing the syntax highlighting that is available as outlined in the [README](https://github.com/KronicDeth/intellij-elixir#syntax-highlighting) and shown Preferences > Editor > Colors & Fonts > Elixir? Finally, does the final have an `.ex` extension?  Only `.ex` is registered an Elixir file extension currently.  If you see any difference in color at all in an .ex file, such as the comments being a different color (light gray) compared to the text or the red squiggle underline for errors, the plugin is working.

There's no auto-complete yet.  In order to have auto-complete I need to [resolve references](https://confluence.jetbrains.com/display/IntelliJIDEA/Reference+Contributor), which is built on top of the [parser](https://github.com/KronicDeth/intellij-elixir/blob/master/src/org/elixir_lang/Elixir.bnf) that still has [outstanding issues](https://github.com/KronicDeth/intellij-elixir/issues?q=is%3Aopen+is%3Aissue+label%3Aparser).

**Comment by KronicDeth** [comment]
Opened issues to add the completion contributors since although they are in the [Custom Language Support guide](https://confluence.jetbrains.com/display/IntelliJIDEA/Custom+Language+Support), they weren't opened as issues that users like you, @michaelbuckner, could see them as planned work for intellij-elixir.
