### ISSUE TITLE
Mix ExUnit test, executable path is empty in Small IDEs

### ISSUE THREAD

**Issue by JanStevens** [KronicDeth/intellij-elixir#853]
Using Rubymine with v6.2.0

```
RubyMine 2017.2.4
Build #RM-172.4155.44, built on September 26, 2017
Licensed to PlayPass NV / Jan Stevens
Subscription is active until November 8, 2017
JRE: 1.8.0_152-release-915-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6
```

On OTP 20.1 and Elixir 1.5.2. I have the path to mix correctly configured, the version is correctly extracted but I'm unable to run any mix tests in rubymine. In version 6.1.0 I could use `CTRL + SHIFT + R` to `Run context configuration` inside a test file to run the test. In 6.2.0 I get a warning saying that `Mix ececutable path is empty`

![screen shot 2017-10-17 at 10 57 47](https://user-images.githubusercontent.com/1540483/31655799-53180816-b32a-11e7-96ed-775790041fea.png)

**Comment by KronicDeth** [comment]
Small IDEs (the non-IntellIJ ones) like Rubymine, don't use the same Project and SDK tracking structure.  I changed how SDKs work in 6.2.0 to support setting an Internal Erlang SDK, so you can set the path to Erlang AND the path to Elixir, so that probably broke some shared code that the Small IDEs still use.

## Fix Proposals
1. Find the minimal bug fix to make Rubymine (and other Small IDEs) work with the test runner changes from 6.2.0 and release 6.2.1 (or 6.3.0 if I add regression tests, those count as Enhancements, so bump the `MINOR` version number)
2. Add better SDK management to 

(1) is faster, but (2) is something I was thinking about doing prior to 6.2.0, but I wanted to get 6.2.0 to stop all the duplicates of #803 from showing up.

![screen shot 2017-10-17 at 7 14 39 am](https://user-images.githubusercontent.com/298259/31664453-159552ec-b30b-11e7-9238-a019965d231a.png)
![screen shot 2017-10-17 at 7 14 33 am](https://user-images.githubusercontent.com/298259/31664458-1af3ac52-b30b-11e7-8290-f2d359a902b1.png)

Looking at the install base numbers, Rubymine installs are actually higher than IntelliJ installs, so I probably should bite the bullet and attempt (2).  I'll try (1) quickly to see if it's less than a week's work.  If it's too incompatible with 6.2.0, I'll switch to (2) and the fix will take longer, but Rubymine  (and other Small IDEs) will (hopefully) end up with a comparable Elixir SDK manager to how Rubygems are managed in Rubymine now.  Until either (1) or (2) is ready, use one of the work-arounds below.

## Work-arounds
1. [Download](https://www.jetbrains.com/idea/download/download-thanks.html?code=IIC) and install IntelliJ IDEA Community Edition for free and run the plugin from it
2. [Download](https://www.jetbrains.com/idea/download/download-thanks.html) and install IntelliJ IDEA Ultimate Edition
  * Use the 30-days trial
  * Upgrade to the All Products Pack if you like it after 30-days, so you can use Rubymine for Ruby and IntelliJ for Elixir (and really any language, even Ruby, Ultimate Edition does them all)
  * Ride the EAPs to get free licenses.  If you install the EAP (Early Access Preview) of any JetBrains IDE, you get a free license for it while testing, but you may hit other bugs because it's not released yet.
3. Downgrade to v6.1.1 of intellij-elixir in the Rubymine

**Comment by psteininger** [comment]
@KronicDeth could we get a patch release that addresses this issue? It's been quite frustrating having lost the ability to run/debug. Thank you in advance!
