### ISSUE TITLE
Please, Please, Please turn off indents more than number of specified in code style.

### ISSUE THREAD

**Issue by twajjo** [KronicDeth/intellij-elixir#913]
The Elixir plugin ignores the settings for indentation and line continuation, favoring the "line everything up like I'm working on a freaking spreadsheet" style that programmers waste time on.

Instead of this monstrosity:

  def init(factor_sources, offer_rules) do
    state = %{sources: factor_sources, 
      rules: (offer_rules |> Map.to_list |> :queue.from_list, 
                                             rule_count: Enum.count(offer_rules), 
                                                                   offers: %{}}
  end

I just want this (indented only 2 spaces for subsequent lines from the parent line):

  def init(factor_sources, offer_rules) do
    state = %{sources: factor_sources, 
      rules: (offer_rules |> Map.to_list |> :queue.from_list, 
      rule_count: Enum.count(offer_rules), 
      offers: %{}}
  end

It worked fine under version 5.

Frankly, the cult of indentation to "line things up" has got to be the worst habit and waste of programmer time that exists, because it causes geeks to pedantically try to line things up again if the length of an argument changes.  Code "lined up" lets reviewers shirk their duties of actually reading code because it gives them a sense of "ooh, pretty!" rather than comprehension.  Code should be read like this paragraph, top to bottom, left to right.  We don't line up all the "the"s in the code, now do we?  That would be a distraction from reading and comprehending the content.

Indent 2 is just fine-- I'm not trying to create a freaking spreadsheet, just write code that is legible and will be read.

I have tried setting all the different options in the Editor Code Style Elixir tab and it has no effect.  Please do not force this hideous and wasteful style on the whole community.

Thanks,
Jeff Osborn

**Comment by KronicDeth** [comment]
Your examples, as posted on Github, don't look any different.  If you want to preserve spacing on Github, you need mark them as Markdown code blocks by surrounding them with triple backquotes.

**Comment by twajjo** [comment]
Great.  I saved my issue and all the extra spaces were removed.  Attached screen captures of code instead.
<img width="497" alt="written_by_vertebrates_with_opposable_thumbs" src="https://user-images.githubusercontent.com/74417/33086326-753c702c-cea4-11e7-88ba-1ef6250e1127.png">
<img width="597" alt="utter_crap" src="https://user-images.githubusercontent.com/74417/33086327-7551866a-cea4-11e7-9958-3b8dce4838f7.png">

**Comment by KronicDeth** [comment]
It looks like the code is missing a closing `)` for the `(` after `rules:`, so it's doing it's best to try to indent the invalid code.

**Comment by twajjo** [comment]
Does not matter.  Still indents wrong with the parens.

**Comment by KronicDeth** [comment]
## Missing `)`

Without the `)`, typing in the order the code is written:

![screen shot 2017-11-21 at 11 18 11 am](https://user-images.githubusercontent.com/298259/33086652-d6286504-cead-11e7-99b8-bceb6b8accc3.png)

Adding the `)` after `:queue.from_list`

![screen shot 2017-11-21 at 11 20 14 am](https://user-images.githubusercontent.com/298259/33086686-fc219b2c-cead-11e7-99fd-a09ad750aeed.png)

Code > Auto-Indent Lines

![screen shot 2017-11-21 at 11 27 58 am](https://user-images.githubusercontent.com/298259/33087051-19975bbe-ceaf-11e7-9878-ab7e63d4e687.png)

Gets the 2 you want.

## `)` Not missing

If instead of missing the `)` and I allow the auto-insert to happen

![screen shot 2017-11-21 at 11 22 13 am](https://user-images.githubusercontent.com/298259/33086858-9281171e-ceae-11e7-9f73-f915f47645c4.png)

![screen shot 2017-11-21 at 11 22 49 am](https://user-images.githubusercontent.com/298259/33086861-9736880c-ceae-11e7-9354-633c0391b2bb.png)

![screen shot 2017-11-21 at 11 23 33 am](https://user-images.githubusercontent.com/298259/33086872-9ca8a68a-ceae-11e7-8fdb-2d4d3265497d.png)

The Code > Auto-Ident Lines

![screen shot 2017-11-21 at 11 24 03 am](https://user-images.githubusercontent.com/298259/33086887-abbe706e-ceae-11e7-8c68-1c099cbd350d.png)

Gets the 2 format you want.

**Comment by twajjo** [comment]
Then why do I get something different?  It worked fine until I installed the latest plugin.

What are your code-style tab settings for Elixir?

Here are mine:

![image](https://user-images.githubusercontent.com/74417/33087219-2c3fcdb2-cea7-11e7-8e24-1f9b04e2f3cd.png)

![image](https://user-images.githubusercontent.com/74417/33087245-43d47c66-cea7-11e7-9f72-89334ee212ee.png)

![image](https://user-images.githubusercontent.com/74417/33087268-54b17f0c-cea7-11e7-9371-be5567810923.png)

![image](https://user-images.githubusercontent.com/74417/33087298-63950142-cea7-11e7-8e53-70f526ae9ee4.png)

I'm using Rubymine with the Ideavim (vim emulator) plugin.  Are you depending on any other plugins, like Erlang?

**Comment by KronicDeth** [comment]
I'm using the default settings, inside IntelliJ (seriously, IntelliJ Community is free and you can manage SDKs easier than in single-language IDEs like Rubymine).  It looks like you unchecked everything on the Wrapping and Braces tab.  The default have those checked.  Try going back to the defaults (since you're running with modified setting with the name Default (1)) and see if you still have the problem.

**Comment by twajjo** [comment]
Well, you shoulda seen how hideous those things were with those options checked.  I think it may be time to scotch my rubymine and re-install from scratch.  I'm guessing at this time that there must be some cruft in the settings that are borking me up.  Thanks for looking at it.

**Comment by gisborne** [comment]
I still have these same problems.
