### ISSUE TITLE
Extreme unresponsivness

### ISSUE THREAD

**Issue by edouardmenayde** [KronicDeth/intellij-elixir#967]
I have been using Webstorm for a while now with javascript/node project and never had a single performance problem.
Since I started trying elixir I noticed little lags while coding in webstorm but did not pay much attention until the last update : Webstorm just completely freeze for no reason (opening a file...) and when doing certain actions such as typing `backspace` I notice a lag. Needless to say I can't code in this situation thus I started trying vscode, sublime with elixir plugins and I don't experience similar problems. I did not want to blame the plugin too fast thus I reinstalled webstorm completly and tried again and it did not fix anything. I tried to invalidate caches and restart, deleting .idea, marking everything as excluded (which is sth I did not notice existed until now : I think we can attribute to this some of the lags I notice at first), I also tried giving more ram to webstorm (512MB -> 8GB). I must admit I lack appropriate knowledge to give you more information about how to help you understand the problem more.

```
=====PERFORMANCE SUMMARY=====
System Info:
Number of CPU: 8
Used memory: 89Mb 
Free memory: 34Mb 
Total memory: 123Mb 
Maximum available memory: 8125Mb 

IDE Info:
Custom plugins: [Elixir (7.1.0), Markdown support (173.2696.26)]
Disabled plugins:[]
Build version: WebStorm 2017.3.2 Build #WS-173.4127.31 December 26, 2017
Java version: 1.8.0_152-release-1024-b8amd64
Operating System: Linux (4.14.5-1-arch, amd64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o
```

**Comment by KronicDeth** [comment]
So it's not a memory problem since you're only using 123Mb, so the other thing to check is if it's a CPU problem.  Some users in the past have reported that `mix credo` was eating their CPU, which is run by the credo annotator.  Try [turning off the credo annotator](https://github.com/KronicDeth/intellij-elixir#configuration) and see if that helps.  

If it doesn't, then I'd need access to a repo that exhibits the performance problems to debug against locally.

**Comment by edouardmenayde** [comment]
@KronicDeth Turning off the credo annotator completly fixed the problem, however I don't understand how this feature could affect performance so badly : is that a plugin related bug or does the problem lie in credo's code ?

**Comment by KronicDeth** [comment]
It depends on the specific project, but mostly it's a problem with `credo` and some of its checks.  Since I'm running `mix credo` in an external process during the "External Annotators" pass on any changed open editor file, it takes however long it takes for `mix credo` to run on that file.  As for why it impacts the responsiveness: I haven't replicated it locally, so I can't say for sure if it's truly blocking in the IDEs OR if `mix credo` is just using so much CPU that your whole computer is becoming unresponsive.  I had assumed since the External Annotator knows you're running an external process that its not blocking and therefore it is just that you're running out of free CPU cycles when `mix credo` runs.

**Comment by edouardmenayde** [comment]
I may have spoken a bit too fast : disabling credo did fix the issue I had when editing a file which is great however it did not fix issues using the UI : `doing searches`, `going through the tests`...
I'm willing to give you access to the repo if it can help.
